### PR TITLE
Mark known issue as resolved  - Visual context menus are cut off when…

### PR DESCRIPTION
**Pull request by laurent-mic**
… using Power BI Embedded

### CODE REVIEW

**Comment by PRMerger8** [comment]
@laurent-mic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@laurent-mic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@mihart 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by KesemSharabi** [comment]
Resolved in this PR:

https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/8273

**Pull request closed without merging**
