### PR TITLE
Update configure-kerberos-powerbi-reports.md

### PR DESCRIPTION
**Pull request by dgosbell**
As a best practice the -S parameter should be used instead of -a as it will check for duplicate SPNs before creating a new one.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@dgosbell : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@maggiesMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by PRMerger15** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
Thanks, @dgosbell! I reviewed with the product team, who gave the go-ahead.
#sign-off

**Pull request merged**
