### PR TITLE
limitations for items included in apps

### PR DESCRIPTION
**Pull request by andreea-s**
contatcs for workspace items don't carry over to apps

### CODE REVIEW

**Comment by PRMerger7** [comment]
@andreea-s : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@andreea-s : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by ktoliver** [comment]
Seeing if I can make the Edit button available by approving; no luck. I'll open a bug for this issue. 

(For a future update: Change "item level" to "item-level" because it's a compound adjective.)

**Pull request merged**
