### PR TITLE
The admins can now enable or disable datamarts to security groups

### PR DESCRIPTION
**Pull request by soheildataviz**
The PBI admins can now enable or disable datamarts capability to the entire organisation or to specific security groups. The current image on Microsoft Docs is outdated. I couldn't upload the new image to the media folder, so I uploaded the file directly here.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@davidiseminger 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.

Note that if you want to use the new image, it will need to be added to the repo as we can't link to external images.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by soheildataviz** [comment]
Any updates on this?

**Comment by Court72** [comment]
@davidiseminger 

Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?

Note that if you want to use the new image, it will need to be added to the repo as we can't link to external images.

Thanks!

**Comment by soheildataviz** [comment]
@Court72 I do not have access to upload the new image, unfortunately. Is there a way that we upload the images to cloud storage such as OneDrive for Business so the content owner can review them before merging the changes?

**Comment by Court72** [comment]
Hi @soheildataviz 

Thanks for your question! The content owner should be able to review the image via the [hyperlink](https://user-images.githubusercontent.com/58403397/190539634-a695ee83-e1a8-4988-989f-2baeec17e441.png) in your changes. No need to upload it at this time.

Thanks!

**Comment by davidiseminger** [comment]
I couldn't get the image to build properly here, so I updated this article in my own PR. Should go live today - thanks for the update!

**Pull request closed without merging**
