### PR TITLE
New look

### PR DESCRIPTION
**Pull request by sovijay**

### CODE REVIEW

**Comment by sovijay** [comment]
@maggiesMSFT here's the outline of the article for new look. it covers all the changes, elaboration on each change is still pending. sending for review as this is my first time with powerbi docs article.

**Comment by jborsecnik** [comment]
@kfile - please take a look. If you want to proceed, this should be moved to the private repo. Thanks.

**Comment by maggiesMSFT** [comment]
Hi, @jborsecnik & @kfile -- @sovijay & I are working on this article. I'll recreate it in the private repo. No further action necessary for either of you. Thx!

**Comment by maggiesMSFT** [comment]
Content recreated in private repo, https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2263

**Pull request closed without merging**
