### PR TITLE
Update service-admin-auditing.md

### PR DESCRIPTION
**Pull request by KayUnkroth**
Added a comparison item to highlight that the activity log discards all existing data when the tenant is moved, while the audit log does not.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@KayUnkroth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @KayUnkroth - Internal contributors who work in the Product Manager role should work in the private repository for advanced quality validations and staging (you also can sign off directly in the private repo). To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. Would you make the updates in the private repo? We'll close this PR. Thanks!

**Comment by ktoliver** [comment]
@kayunkroth @kfollis Per email, we can keep the requested update in this PR. The PR review team can merge after the content team signs off, per the process in the public repository.

**Comment by kfollis** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
