### PR TITLE
Update service-r-visuals.md

### PR DESCRIPTION
**Pull request by otarb**
Updating to reflect R engine version

### CODE REVIEW

**Comment by PRMerger19** [comment]
@otarb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@otarb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Pull request merged**
