### PR TITLE
Update service-template-apps-create.md

### PR DESCRIPTION
**Pull request by teddybercovitz**
Update process to reflect the dependency between PowerBI release management and CPP

### CODE REVIEW

**Comment by PRMerger10** [comment]
@teddybercovitz : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@maggiesMSFT  - can you take a look at the submitted changes?  (i note that there are 2 links with 'en-us' locales that will need be removed before the PR can be merged). if there are no other changes you want from @teddybercovitz , i can change them. thanks.

**Comment by PRMerger7** [comment]
@maggiesMSFT : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off
I made some other changes, just realized I didn't delete the "en-us". Yes, please delete. Thanks!

**Comment by PRMerger12** [comment]
@maggiesMSFT : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off 
again.
deleted the en-us  in the links

**Comment by PRMerger6** [comment]
@maggiesMSFT : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@Jak-MS : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Jak-MS : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Pull request merged**
