### PR TITLE
Update scheduled-refresh.md

### PR DESCRIPTION
**Pull request by gboreki**
Added note about limitation of dynamic datasources in Power Bi Report Server

### CODE REVIEW

**Comment by PRMerger9** [comment]
@gboreki : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
#sign-off 
Thanks, @gboreki !

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
