### PR TITLE
typo: powerbi-docs/sql-server-analysis-services-tabular-data.md

### PR DESCRIPTION
**Pull request by nschonni**
- adminsitrator -> administrator
- swtiched -> switched

### CODE REVIEW

**Comment by PRMerger10** [comment]
@nschonni : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by rjagiewich** [comment]
Verified editorial corrections.

**Comment by PRMerger20** [comment]
@rjagiewich : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@rjagiewich : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Pull request merged**
