### PR TITLE
JS Dev Center metadata

### PR DESCRIPTION
**Pull request by diberry**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@diberry : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by diberry** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@diberry: I'm sorry - only the author of this article, @KesemSharabi, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @diberry - Would you make this content update in the private repo? Thank you! We'll close this PR.

**Pull request closed without merging**
