### PR TITLE
Updating prerequisites section.

### PR DESCRIPTION
**Pull request by v-jkorsi**
Ticket or request : https://msazure.visualstudio.com/EnvironmentSustainabilityGreenSKU/_workitems/edit/9049963

### CODE REVIEW

**Comment by PRMerger6** [comment]
@v-jkorsi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@paulinbar: I'm sorry - only the author of this article, @andreabichsel, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by andreabichsel — COMMENTED** [review]
Approved

**Comment by andreabichsel** [comment]
I only see an option to leave comments, not the Approve option that I see in other repos where I have more permissions. @paulinbar, do you know if it matters which of us sends the mail to the techdocprs alias?

**Pull request merged**
