### PR TITLE
Update service-admin-failover.md

### PR DESCRIPTION
**Pull request by DavidMagarMS**
Updates to include an extreme failover scenario for gw config

### CODE REVIEW

**Comment by PRMerger15** [comment]
@DavidMagarMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@kfollis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@DavidMagarMS Hi. This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We'll keep this PR open for review and merge, but in the future, would you make content updates in the private repo? Thanks!

**Comment by PRMerger8** [comment]
@kfollis : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
