### PR TITLE
Update desktop-accessibility-keyboard-shortcuts.md

### PR DESCRIPTION
**Pull request by tessahurr**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@tessahurr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @tessahurr - Program Managers are expected to work in the private repo. To submit an update in the private repo from within the documentation. after you select **Edit** on the article page, add "-pr" to the URL. We'll keep this PR in the public repo for review, but could you work in the private repo in the future? Many thanks.

**Comment by PRMerger16** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Pull request merged**
