### PR TITLE
URL filters in SharePoint

### PR DESCRIPTION
**Pull request by premradhakrishnan**
Clarify that we can filter reports via the URL in SharePoint by using the <iframe> embed option.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@maggiesMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
thanks, @premradhakrishnan ! I'm checking with the product team.

**Comment by maggiesMSFT** [comment]
Hi @premradhakrishnan -- the product team says, 
"We don't test the iFrame web part with Power BI so we couldn't support it." 
So I'm not going to add this. Thanks though!

**Comment by premradhakrishnan** [comment]
Hi Maggie,

The filter URLs work normally on the browser which is tested and supported. So it will always work within the iframe even if it’s not tested.

If you could reconsider, I think adding that line would help a lot of others who have asked similar questions.

Thank you
Prem

iOS
________________________________

**Comment by maggiesMSFT** [comment]
Hi @premradhakrishnan -- I checked again; answer is the same. We don't test the iFrame web part with Power BI so we couldn't support it.
Thanks though!

**Comment by premradhakrishnan** [comment]
No worries. Thank you for checking.

iOS
________________________________

**Pull request closed without merging**
