### PR TITLE
fix: Remove encoding characters

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@nschonni : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by nschonni** [comment]
The GitHub diff might not show much, but these are hidden characters shown in VS Code. Probably left over from utf-16 to utf-8 conversion

**Comment by ktoliver** [comment]
Verified in XML; looks correct.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Pull request merged**
