### PR TITLE
Update for Org store GA

### PR DESCRIPTION
**Pull request by tsikiksr**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@tsikiksr : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by ben-howard** [comment]
Please check the spelling, I noticed vesrion instead of version.

**Comment by PRMerger9** [comment]
@tsikiksr : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by markingmyname** [comment]
Close PR, please.  Creating a new PR for this change.

**Comment by maggiesMSFT** [comment]
closing per @markingmyname

**Pull request closed without merging**
