### PR TITLE
Update service-roles-new-workspaces.md

### PR DESCRIPTION
**Pull request by meenalsri**
Added note about workspace member limitation.

### CODE REVIEW

**Comment by meenalsri** [comment]
@maggiesMSFT

**Comment by Jak-MS** [comment]
@maggiesMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
Hi @Jak-MS -- I approve but suddenly Github doesn't think I'm a Microsoft employee. So consider this me signing off. 
Thx!

**Pull request merged**
