### PR TITLE
Update service-basic-concepts.md

### PR DESCRIPTION
**Pull request by siva44**
There was an icon missing in the below line,
a chevron **icon () t**o display the My Workspace scrollable list of dashboards, reports, workbooks, and datasets

I have added.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@siva44 : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off for @mihart

**Comment by PRMerger16** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @mihart, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger16** [comment]
@maggiesMSFT : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Pull request merged**
