### PR TITLE
Update end-user-subscribe.md

### PR DESCRIPTION
**Pull request by rabysani**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@rabysani : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@mihart, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

**Comment by mibruhje** [comment]
@rabysani Two things: 

1) Let's leave this comment under the "Power BI administrators" > "Subscription controls and tracking for administrators" section. 

2) Let adjust the wording to the following, including a link to the doc page where info on the relevant admin switches lives.

[Enable specific attachment formats](https://docs.microsoft.com/power-bi/admin/service-admin-portal-export-sharing#export-to-excel) for paginated report subscriptions (PDF, PowerPoint presentation (PPTX), Excel Workbook (XLSX), Word Document (DOCX), CSV file, and XML).

**Comment by PRMerger7** [comment]
@rabysani : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@rabysani : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@rabysani : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by PRMerger13** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @mihart, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
