### PR TITLE
Update dataview-mappings.md

### PR DESCRIPTION
**Pull request by brokolica**
The capabilities.json didn't contain the correct kind of the data role for the given set of data in the example below. The kind has to be of type "Grouping" otherwise it is always processed by some aggregation function like Count, First, etc. in Power BI (we really don't want this because we can't get to all the data passed to our custom visual - we always get first/count/etc. and no all raw data).

### CODE REVIEW

**Comment by PRMerger19** [comment]
@brokolica : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@KesemSharabi - Could you review the proposed change? Thanks.

**Comment by KesemSharabi** [comment]
Hi @brokolica,

Thanks for your comments and apologies for the late response.

I asked the Power BI visuals development team to look into your comments before I accept the change.

**Comment by KesemSharabi** [comment]
Hi @uve - can you please take a look at the proposed change?

Thanks,

Kesem

**Comment by uve** [comment]
@KesemSharabi, please merge this PR.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
closing/reopening to try to get CLA check to finish running

**Comment by KesemSharabi** [comment]
Hi @brokolica,

I checked with our development team and you're correct - thanks for flagging this.

#sign-off

**Pull request merged**
