### PR TITLE
Removing documents for AS Engine Template App

### PR DESCRIPTION
**Pull request by saurabhr14**
Removed usage and installation guide documents for AS Engine Template App since it has stopped distribution through AppSource.

### CODE REVIEW

**Comment by American-Dipper** [comment]
@kesharab , @davidiseminger - Can you review the proposed changes?  

***Note: Redirects and TOC deletions would also have to be made for these articles to be deleted.***

 
IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  

 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by saurabhr14** [comment]
Hi @David ***@***.***>

Is there any update on below PR for AS Engine documentation?

Thanks and Regards,

Saurabh Ruikar

**Comment by saurabhr14** [comment]
Hi there,

In order to remove this content, we'll need internal confirmation that we should remove those articles. Doing so here (in this email thread) will suffice, but a request through a public PR to remove content isn't something we approve without confirmation.

It can be easy - have the PM who owns that feature weigh in here, in this thread, and approve the two docs' removal.

Thanks,
-David
________________________________
From: Saurabh Ruikar (ALLYIS INC) ***@***.***>
Sent: Thursday, April 27, 2023 6:54 AM
To: MicrosoftDocs/powerbi-docs ***@***.***>; David Iseminger ***@***.***>
Cc: Kishan Pujara (ALLYIS INC) ***@***.***>; Bogdan Blaga ***@***.***>; Kesem Sharabi ***@***.***>
Subject: RE: [MicrosoftDocs/powerbi-docs] Removing documents for AS Engine Template App (PR #4450)


Hi @David ***@***.***>

Is there any update on below PR for AS Engine documentation?

Thanks and Regards,

Saurabh Ruikar

**Comment by saurabhr14** [comment]
Adding @Christian ***@***.***> to confirm the removal of this documentation: BYOLA AS Engine Template App

Bogdan Blaga
Senior Program Manager
Power BI Service Platform

***@***.***

**Comment by saurabhr14** [comment]
Hey all -- this is in-process right now with the PM owner, Rui. We can close this thread.
________________________________
From: Bogdan Blaga ***@***.***>
Sent: Tuesday, May 2, 2023 2:02 PM
To: David Iseminger ***@***.***>; Saurabh Ruikar (ALLYIS INC) ***@***.***>; MicrosoftDocs/powerbi-docs ***@***.***>; Christian Wade ***@***.***>
Cc: Kishan Pujara (ALLYIS INC) ***@***.***>; Kesem Sharabi ***@***.***>
Subject: RE: [MicrosoftDocs/powerbi-docs] Removing documents for AS Engine Template App (PR #4450)


Adding @Christian ***@***.***> to confirm the removal of this documentation: BYOLA AS Engine Template App



Bogdan Blaga

Senior Program Manager

Power BI Service Platform



***@***.***

**Comment by davidiseminger** [comment]
In progress on another PR.

**Pull request closed without merging**
