### PR TITLE
Update service-r-packages-support.md

### PR DESCRIPTION
**Pull request by JesseSingleton**
Removed duplicate R package references where name, package version and url are identical.

Removed:
* class 7.3-14
* cluster 2.0.6
* iterators 1.0.8
* lattice 0.20-35
* matrix 1.2-10
* nlme 3.1-131
* nnet 7.3-12
* png 0.1-7
* rodbc 1.3015
* survival 2.41-3

### CODE REVIEW

**Comment by PRMerger18** [comment]
@JesseSingleton : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
