### PR TITLE
typo: Double word "the"

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@TrishaMc : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@TrishaMc : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by TrishaMc** [comment]
Verified editorial fix.

**Pull request merged**
