### PR TITLE
Update service-admin-premium-multi-geo.md

### PR DESCRIPTION
**Pull request by Chandrika311**
As per the ICM here  Incident-281933629 Details - IcM (microsofticm.com) , we learnt that score cards are not supported. Please review and push the changes
CC:@KesemSharabi

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@Chandrika311 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by KesemSharabi** [comment]
Hi @Chandrika311,

I've asking the PM to confirm, and will then update the document.

Thanks,

Kesem

**Comment by PRMerger6** [comment]
@KesemSharabi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
