### PR TITLE
Update service-self-service-signup-for-power-bi.md

### PR DESCRIPTION
**Pull request by haydnr**
Completed editing and reviewing this document and added some To Dos about creating content around the Individual Power BI Pro Trial and adding content about self-serve purchase to this document.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@haydnr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
