### PR TITLE
Update reference to incorrect table name

### PR DESCRIPTION
**Pull request by jasonhendrix**
Example should refer to Payroll table rather than Salary table

### CODE REVIEW

**Comment by PRMerger9** [comment]
@jasonhendrix : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]
approve

**Comment by PRMerger19** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Hi, @jasonhendrix -- good eye and good catch! I've accepted your change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @peter-myers, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
