### PR TITLE
Update refresh-scheduled-refresh.md

### PR DESCRIPTION
**Pull request by jayendranarumugam**
Updated with additional info about scheduled refresh note

### CODE REVIEW

**Comment by PRMerger12** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
