### PR TITLE
Update service-admin-licensing-organization.md

### PR DESCRIPTION
**Pull request by haydnr**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@haydnr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
