### PR TITLE
Updating GetDate mechanism from Workspace DoneDrive

### PR DESCRIPTION
**Pull request by soheildataviz**
Added Workspace OneDrive Get Data mechanism.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@maggiesMSFT 
- Can you review this PR?

Keep in mind that images hosted outside the repo aren't allowed.

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by soheildataviz** [comment]
@Jak-MS I tried to upload the images into the repo but I couldn't find the related folder to do so.

**Comment by Jak-MS** [comment]
@soheildataviz - this is the folder for the article you're modifying: ` /powerbi-docs/powerbi-docs/collaborate-share/media/service-create-the-new-workspaces/`

**Comment by soheildataviz** [comment]
> @soheildataviz - this is the media folder for the article you're modifying: ` /powerbi-docs/powerbi-docs/collaborate-share/media/service-create-the-new-workspaces/`

Thank you @Jak-MS. But uploading file is disabled on this folder.
image

**Comment by Jak-MS** [comment]
@soheildataviz - understood. I can't fix that issue. 

We'll wait for the review from @maggiesMSFT ... and if your changes are approved, she'll need to upload the images files.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
add these back:
Screenshot of Get Data from workspace OneDrive.

Screenshot of Connecting to Power BI file stored in workspace OneDrive.

**Comment by maggiesMSFT** [comment]
#sign-off

**Pull request merged**
