### PR TITLE
Update service-gateway-sso-kerberos.md

### PR DESCRIPTION
**Pull request by AdamBJ**
Removing unnecessary characters configuration file paths

### CODE REVIEW

**Comment by PRMerger10** [comment]
@AdamBJ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@v-shils : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
