### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from repo_sync_working_branch to live.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@huypub : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@huypub : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@mgblythe : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@huypub : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@mgblythe : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Pull request merged**
