### PR TITLE
Clarify cross-privacy level folding behaviors

### PR DESCRIPTION
**Pull request by bgribaudo**
The current descriptions given for privacy levels imply a stronger level of isolation than actually is/needs to be maintained by Power Query.

For example, level private's behavior is currently described as "[a] private data source is completely isolated from other data sources". However, in actuality, private sources are not **completely** isolated, as it is possible for data from other sources to be folded to them (but not the other way around).

This edit attempts to clarify folding behaviors across data sources.

Reference: https://github.com/microsoft/DataConnectors/issues/457

### CODE REVIEW

**Comment by PRMerger9** [comment]
@bgribaudo : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by davidiseminger** [comment]
Thanks for the contribution, and the reference to the authoritative answer, @bgribaudo !

**Comment by bgribaudo** [comment]
Thanks, @davidiseminger!

**Pull request merged**
