### PR TITLE
Added `pbiviz --create-cert` step

### PR DESCRIPTION
**Pull request by SarahSexton**
Also fixed `<a name="ssl-setup"></a>` HTML typo

### CODE REVIEW

**Comment by PRMerger9** [comment]
@SarahSexton : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@SarahSexton : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by markingmyname** [comment]
@SarahSexton Can you get the branch up-to-date?  If so, then i can sign-off.

**Comment by PRMerger15** [comment]
@SarahSexton : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
