### PR TITLE
Update service-create-distribute-apps.md

### PR DESCRIPTION
**Pull request by nachiketkmaat**
Added comments in brackets to help documentation team to add more context

### CODE REVIEW

**Comment by maggiesMSFT** [comment]
Hi @nachiketkmaat -- Thanks for asking. I've passed the question on and hope to come up with more information for you. Thanks!

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by paulinbar** [comment]
@maggiesMSFT , can you check to see whether this has been resolved and close it issue if it has? Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @nachiketkmaat -- thanks! I updated the article in another PR so I could make a few changes. Update should be live tomorrow afternoon Pacific time, Sept 8.

**Pull request closed without merging**
