### PR TITLE
Update compare-report-server-service.md

### PR DESCRIPTION
**Pull request by ryoma-nagata**
There is a potential misunderstanding about the license that allows the Power BI Report server to be deployed to the Azure shared host by the current SA.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ryoma-nagata : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Hi, @ryoma-nagata -- I believe I sent you an email asking for more info. Did you receive it? If not, then I have the wrong email for you. Please let me know.

**Comment by ryoma-nagata** [comment]
Hi, @maggiesMSFT 
I haven't received any emails, please check the Public Email Address of Git that I published.

**Comment by maggiesMSFT** [comment]
Hi, @ryoma-nagata -- Ah, OK, thanks for letting me know! 
The message was: I checked with the product team. They are not aware of any such change. Could you explain why you’re adding that sentence?

**Comment by ryoma-nagata** [comment]
Hi, @maggiesMSFT 
My customer having SQL Server EE, including SA, wanted to host Power BI Report Server on Azure, so I did some research on the license.
Our research showed that only past SAs prior to the terms change is allowed to deploy PowerBIReport Server on Azure, and currently it is not allowed to be hosted in the cloud except for Power BI Premium licenses.
I added this sentence because I want to reduce the pain of researching customers with similar needs.
If the sentence I added is correct, please add it.

**Comment by maggiesMSFT** [comment]
Hi @ryoma-nagata -- I checked with the product team again, and according to them, it is not correct. So I'm closing this PR. But thanks for submitting it!

**Comment by ryoma-nagata** [comment]
HI, @maggiesMSFT 
Thank you for chacking.
Does that mean it's ok to configure Power BI Report Server on an Azure VM as long as we have SQL Server Enterprise with Software Assurance?

**Comment by maggiesMSFT** [comment]
Hi, @ryoma-nagata -- the answer to your question, "Does that mean it's ok to configure Power BI Report Server on an Azure VM as long as we have SQL Server Enterprise with Software Assurance?"
is Yes. 
I'm updating the article to link to the Volume Licensing page, https://www.microsoftvolumelicensing.com/DocumentSearch.aspx?Mode=3&DocumentTypeId=1&ShowArchived=True 
The update will be live tomorrow afternoon.
Thanks!

**Comment by ryoma-nagata** [comment]
Hi, @maggiesMSFT 
I understand.Thanks!

**Pull request closed without merging**
