### PR TITLE
fix incorrect docs for parameterPanel

### PR DESCRIPTION
**Pull request by andresdlpsMsft**
fixing incorrect name for the url parameter to control the parameter Panel for RDL

### CODE REVIEW

**Comment by PRMerger14** [comment]
@andresdlpsMsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]
approved

**Comment by PRMerger9** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
