### PR TITLE
typo: datasest -> dataset

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by rjagiewich** [comment]
Verified editorial corrections.

**Comment by PRMerger9** [comment]
@rjagiewich : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by rjagiewich** [comment]
Verified editorial corrections.

**Comment by PRMerger9** [comment]
@rjagiewich : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Pull request merged**
