### PR TITLE
Update description of Query Memory Limit and Query Timeout settings

### PR DESCRIPTION
**Pull request by minghan**
Update description of Query Memory Limit and Query Timeout settings

### CODE REVIEW

**Comment by PRMerger15** [comment]
@minghan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@minghan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@minghan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@minghan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@minghan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@minghan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@minghan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by minghan** [comment]
#sign-off

**Comment by ktoliver** [comment]
@davidiseminger Could you review the proposed changes? Thanks.

**Pull request merged**
