### PR TITLE
Link fixes

### PR DESCRIPTION
**Pull request by nschonni**
Sorry, this touches a bunch of files but each commit fixes a different thing.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@nschonni : Thanks for your contribution! The author, @SarinaJoan, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @SarinaJoan, has been notified to review your proposed change.

**Comment by mgblythe** [comment]
Thanks @nschonni! #sign-off

**Comment by PRMerger18** [comment]
@mgblythe: I'm sorry - only the author of this article, @SarinaJoan, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
