### PR TITLE
update AnalyzedByExternalApplication

### PR DESCRIPTION
**Pull request by jtarquino**
The event generated every time the Analyze in Excel endpoint is consumed is AnalyzedByExternalApplication

### CODE REVIEW

**Comment by PRMerger10** [comment]
@jtarquino : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jtarquino** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
