### PR TITLE
Updated service-embed-secure.md

### PR DESCRIPTION
**Pull request by ravisrao**
External guest users with Azure business to business support was provided from Dec 2019

### CODE REVIEW

**Comment by PRMerger19** [comment]
@ravisrao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
Thanks, @ravisrao !

**Comment by ravisrao** [comment]
Thanks for the merge.
When will this be live on the actual documentation? How long does it take for merged changes to reflect

Thanks,
Ravi

**Comment by maggiesMSFT** [comment]
Hi, @ravisrao -- should be live now, or shortly, depending on updating the various servers.

**Pull request merged**
