### PR TITLE
Change the Dataset to Semantic Model

### PR DESCRIPTION
**Pull request by VahidDM**
Microsoft has renamed the Power BI dataset content type to semantic model, so I have updated this document by replacing Dataset to Semantic Model.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@mberdugo 

To verify that these changes follow Microsoft style, see the [capitalization guidelines](https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357). 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by mberdugo** [comment]
Hi, @VahidDM and @ShannonLeavitt. 
Thanks for bringing this to my attention. As I understand it, this article deals with push datasets and push datasets aren't in scope to be changed. You can see here for more information. [New name for Power BI datasets](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-rename). So I think we should leave the article as is.

**Comment by VahidDM** [comment]
@mberdugo  
Hi
That document needs to be updated as well ( I already updated that and submitted the request). All streaming datasets are now streaming semantic models, check out this link:

https://learn.microsoft.com/en-us/power-bi/connect-data/service-real-time-streaming#types-of-real-time-semantic-models

And see this image from Power BI service (Fabric):
image

**Comment by ShannonLeavitt** [comment]
Thanks @mberdugo. If this PR should be closed, could you add a `#please-close` command?

**Review by paulinbar — APPROVED** [review]

**Comment by paulinbar** [comment]
#sign-off

**Pull request merged**
