### PR TITLE
Add redirect_uri to graph security connector

### PR DESCRIPTION
**Pull request by thesauri**
Add `redirect_uri` property to the list of required properties for granting consent to the Graph Security connector. This property is required for granting the permission, but the value wasn't obvious and required some googling to figure out. Hope this saves someone a minute or two :)

### CODE REVIEW

**Comment by PRMerger6** [comment]
@thesauri : Thanks for your contribution! The author(s) have been notified to review your proposed change. @preetikr

**Comment by ktoliver** [comment]
Hi @kfollis - @preetikr isn't set up as a MicrosoftDocs-linked account in GitHub. I'll assign this PR to you (Preeti doesn't appear in the **Assigned** or **Reviewers** options). Thanks.

**Comment by kfollis** [comment]
Reassigning to @davidiseminger to verify with PM. Preeti Krishna (preetikr is MS alias) is a PM in Graph and should be able to confirm the change.

**Comment by PRMerger19** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change. @preetikr

**Comment by PRMerger20** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change. @preetikr

**Comment by PRMerger8** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change. @preetikr

**Pull request merged**
