### PR TITLE
updated input data file size

### PR DESCRIPTION
**Pull request by aphilip94**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@aphilip94 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aphilip94** [comment]
@mihart do you need any further information to sign off on this?

**Comment by PRMerger14** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off 
Thanks, @aphilip94 
cc @mihart

**Pull request merged**
