### PR TITLE
Disclaimer added and page updated

### PR DESCRIPTION
**Pull request by raunakjhawar**
This approach only works with Azure SQL server/database when this is not behind a VNET or has PE enabled. This disclaimer is important.

### CODE REVIEW

**Comment by ktoliver** [comment]
This PR has been added to [bug 36470](https://ceapex.visualstudio.com/Engineering/_workitems/edit/36470) because the checks are failing. We'll watch the PR and assign it when the checks are working.

-PR review team

**Comment by PRMerger17** [comment]
@raunakjhawar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@raunakjhawar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@davidiseminger This PR is ready to review now. Could you take a look? Thanks.

**Comment by PRMerger20** [comment]
@raunakjhawar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
