### PR TITLE
Update desktop-tutorial-row-level-security-onprem-ssas-tabular.md

### PR DESCRIPTION
**Pull request by nisalm**
DimSalesTerritoty and DimUserSecurity Query were wrong. Corrected

### CODE REVIEW

**Comment by PRMerger20** [comment]
@nisalm : Thanks for your contribution! The author, @selvarms, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
@davidiseminger, could you review this change for @selvarms? Thanks!

**Comment by PRMerger6** [comment]
@mgblythe : Thanks for your contribution! The author, @selvarms, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@davidiseminger : Thanks for your contribution! The author, @selvarms, has been notified to review your proposed change.

**Pull request merged**
