### PR TITLE
Update desktop-create-and-manage-relationships.md

### PR DESCRIPTION
**Pull request by vickar**
The default direction type created in PBID is single and not both, hence I've suggested the necessary update

### CODE REVIEW

**Comment by PRMerger9** [comment]
@vickar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@vickar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@vickar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@vickar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
