### PR TITLE
Include link to schema generation documentation

### PR DESCRIPTION
**Pull request by AdamDWilson**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@AdamDWilson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AdamDWilson** [comment]
@juluczni FYI

**Comment by PRMerger19** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
