### PR TITLE
Update service-azure-sql-database-with-direct-connect.md

### PR DESCRIPTION
**Pull request by dcbrown16**
I'm not actually sure how to construct the link such that it will jump to the Azure docs but stay in the language that the user has selected, if someone can make that edit please do so. The link was outdated so I'm pointing it to the current page.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@dcbrown16 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
Thanks for the fix @dcbrown16! If you take /en-us out of the URL, we'll use browser locale to do the right thing. I removed it.

**Comment by mgblythe** [comment]
#sign-off

**Pull request merged**
