### PR TITLE
import IVisualHost to visual.ts

### PR DESCRIPTION
**Pull request by andyparkerson**
In the developing-the-visual-elements section, `IVisualHost` needs to be imported. Otherwise the compiler gives the error:
```
./src/visual.ts
[tsl] ERROR in C:\Users\Andy\pbiviz\circleCard\src\visual.ts(40,19)
      TS2304: Cannot find name 'IVisualHost'.
```

### CODE REVIEW

**Comment by PRMerger14** [comment]
@andyparkerson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
@zBritva can you please confirm that these changes are correct? Thanks.

**Comment by zBritva** [comment]
@KesemSharabi It's correct, but issue already was fixed: https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial#developing-the-visual-elements

**Comment by Jak-MS** [comment]
@KesemSharabi - if the issue is already addressed, let us know if you prefer to close this PR by entering `#please-close` in a comment.  thanks.

**Pull request closed without merging**
