### PR TITLE
QnAMode -> QnaMode

### PR DESCRIPTION
**Pull request by andyparkerson**
Changing the capitalization to match the code

https://github.com/microsoft/PowerBI-JavaScript/blob/5e5455a41327052828da4ed8e58e6a09d1479ff1/dist/powerbi-client.d.ts#L171

### CODE REVIEW

**Comment by PRMerger13** [comment]
@andyparkerson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@andyparkerson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@andyparkerson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@andyparkerson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@andyparkerson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@andyparkerson : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
