### PR TITLE
Update whitepapers.md

### PR DESCRIPTION
**Pull request by jaydeflix**
Whitepaper is not currently a term supported by the Microsoft Style Guide and the two word form, white paper, should be used.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@jaydeflix : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mekmin100** [comment]
evet tesaduf çalışmalar olmakta ama işe yarıyorsa iyi olur ben github tabanları hakkında biraş karışıklık yaşıyom yinede gelişmek isterim

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
Thanks, @jaydeflix ! We've had it wrong all this time!

#sign-off

**Comment by jaydeflix** [comment]
> Thanks, @jaydeflix ! We've had it wrong all this time!
> 
> #sign-off 

Trust me, you're not the only one. No one knows when it changed and I think it's that no one ever looked at the style guide to check.

**Comment by mekmin100** [comment]
insanlık hali meşkül ilgi alakamı hoşgörün iletişim bilgilerimi önemsemekte ve ilgi duymaktayım takip edicem teşekürler.(sinan özçelik)

________________________________
Gönderen: Maggie Sparkman <notifications@github.com>
Gönderildi: 5 Şubat 2021 Cuma 05:12
Kime: MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Bilgi: mekmin100 <aleksisinan@gmail.com>; Comment <comment@noreply.github.com>
Konu: Re: [MicrosoftDocs/powerbi-docs] Update whitepapers.md (#2805)


@maggiesMSFT approved this pull request.

**Pull request merged**
