### PR TITLE
Update service-gateway-sso-kerberos.md

### PR DESCRIPTION
**Pull request by AdamBJ**
Incorporating feedback from open comment. @arthiriyer FYI

### CODE REVIEW

**Comment by PRMerger13** [comment]
@AdamBJ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@jborsecnik : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
This added link is not currently working from the preview. Can you advise? Thanks.

*For more information, see [Windows Authorization and Access Group](/windows/security/identity-protection/access-control/active-directory-security-groups#bkmk-winauthaccess).*

**Comment by mgblythe** [comment]
Hi @jborsecnik - it's a site relative link. It will work in production: https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#bkmk-winauthaccess

#sign-off

**Pull request merged**
