### PR TITLE
Update service-admin-faq.md

### PR DESCRIPTION
**Pull request by haydnr**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@haydnr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
