### PR TITLE
Rename Get-RsRestItemDataModelParameters to Get-RsRestItemDataModelParameter

### LINKED ISSUE #3313: Get-RsRestItemDataModelParameters doesn't exist
The ReportingServicesTools module exposes `Get-RsRestItemDataModelParameter` function, not `Get-RsRestItemDataModelParameters`, making the example [https://docs.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis#update-parameters-using-the-powershell-tools](https://docs.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis#update-parameters-using-the-powershell-tools) invalid.

### PR DESCRIPTION
**Pull request by Lexy2**
Corrected the typos (or recent changes in the PowerShell ReportingServicesTools module) of Get-RsRestItemDataModelParameter query and some numbering mistakes

### CODE REVIEW

**Comment by PRMerger4** [comment]
@Lexy2 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Lexy2 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Lexy2** [comment]
Fixed #3313

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by maggiesMSFT** [comment]
Hi, @Lexy2 -- Verified with the engineers. Thanks!
#sign-off

**Pull request merged**
