### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to live

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by OPS to resolve syncing conflicts from repo_sync_working_branch to live.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@huypub : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@tfosmark : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@tfosmark: I'm sorry - only the author of this article, @maggiesMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger14** [comment]
@huypub : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@huypub : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Pull request merged**
