### PR TITLE
Keyboard nav for visuals

### PR DESCRIPTION
**Pull request by tessahurr**
Added keyboard nav in the shortcuts section for On visual.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@tessahurr : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by tessahurr** [comment]
Hi @davidiseminger, this would go with our March release.  Thanks!

**Comment by PRMerger10** [comment]
@mgblythe : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Jak-MS : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Pull request merged**
