### PR TITLE
Updated some text around "OneDrive" storage location

### PR DESCRIPTION
**Pull request by loryanstrant**
Added some clarifications that it is actually a SharePoint document library, and disclaimer that creation of Groups may be restricted.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@loryanstrant : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by davidiseminger** [comment]
Looks good to me - thanks for the contribution!

#sign-off

**Comment by PRMerger10** [comment]
@davidiseminger: I'm sorry - only the author of this article, @maggiesMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ShannonLeavitt** [comment]
@davidiseminger - The new content presents one issue that needs to be fixed: Line 70 should be formatted as a Markdown callout. Could you make that fix in a new PR in the private repo?

**Pull request merged**
