### PR TITLE
Remove space from visual name

### PR DESCRIPTION
**Pull request by jongio**
Don't want people to think they can put spaces in visual names

### CODE REVIEW

**Comment by PRMerger18** [comment]
@jongio : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by markingmyname** [comment]
Good catch.  #sign-off

**Comment by PRMerger9** [comment]
@jongio : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by markingmyname** [comment]
#sign-off

**Pull request merged**
