### PR TITLE
real-time dataset changed to real-time semantic models

### PR DESCRIPTION
**Pull request by VahidDM**
As the real-time dataset changed to real-time semantic models, I have updated the document

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@KesemSharabi

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by mberdugo — CHANGES_REQUESTED** [review]
Push datasets should remain as push datasets. (See https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-rename) The other changes are approved. Thanks!

**Comment by paulinbar** [comment]
Hi @VahidDM, I believe these instances are not being changed. Checking with the product team and then I'll approve/reject accordingly.

**Comment by Court72** [comment]
> Push datasets should remain as push datasets. (See https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-rename) The other changes are approved. Thanks!
- @mberdugo, I made this change.

> I believe these instances are not being changed. Checking with the product team and then I'll approve/reject accordingly.
- @paulinbar, Thanks. If this PR should be closed instead, add a `#please-close` comment. If it should be merged, add a `#sign-off` comment when it's ready.

**Comment by paulinbar** [comment]
Hi @VahidDM, I checked with the product group. This article https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-rename is correct and up to date. The exceptions to the dataset->semantic model renaming are listed there and are correct, so I am going to leave the article as is. Thanks for taking the interest though in keeping our documentation correct and current! Closing this pull request now.

**Pull request closed without merging**
