### PR TITLE
Update directlake-overview.md

### PR DESCRIPTION
**Pull request by paulturley**
Clarified confusing text related to Direct Lake semantic model limitations and issues. There was a lot of confusion around tables based on SQL views. Many of the limitations described earlier as issues are by-design and not bugs or issues, per-se. The word "yet" suggested that features were forthcoming.

### CODE REVIEW

**Comment by kfollis** [comment]
@davidiseminger - please review the proposed changes in this PR. Looks like good clarifications, but I need you to review/verify the commit

**Comment by davidiseminger** [comment]
These look good, thanks!

#sign-off

**Comment by Jak-MS** [comment]
@paulturley - this PR has developed merge conflicts that we can't address. Can you fix these and tag us for a review and merge? thanks!

fyi @kfollis

**Comment by kfollis** [comment]
@davidiseminger - the Direct Lake content has moved to the Fabric repo. Can you please port this change to that repo and the close this PR?

**Comment by davidiseminger** [comment]
Hello @paulturley -- thanks for this feedback. The article has moved to the Fabric repo so this PR can't be merged, but I made all your changes in the article in its new location. Those updates will show up in the next build, likely later today. 

I'll close this, but note that your changes have been accepted. Thanks!

**Pull request closed without merging**
