### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by jawn**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@jawn : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Merging the typo fix.

Thanks @jawn

**Comment by maggiesMSFT** [comment]
Good catch -- thanks, @jawn!

**Pull request merged**
