### PR TITLE
Fix incorrect breadcrumbs at Power BI developer

### PR DESCRIPTION
**Pull request by liprec**
*Issue*: At https://docs.microsoft.com/en-us/power-bi/developer/ the breadcrumb is **Docs / Power BI / Developer / Use R-powered Power BI visuals in Power BI**
image

*Solution*: remove unnecessary extra items node in yml file to restore breadcrumb to **Docs / Power BI / Developer**

### CODE REVIEW

**Comment by markingmyname** [comment]
@lipre

This branch has a merge conflict.

Please create a new PR or correct the conflict.

Thank you.

**Comment by liprec** [comment]
Hi @markingmyname ,

Branch is updated and check states there are no conflicts at this moment.

-JP

**Comment by ktoliver** [comment]
close/reopen for validation

**Comment by ktoliver** [comment]
close/reopen for validation

**Comment by markingmyname** [comment]
@KesemSharabi, please help with this issue.  Thank you.

@ktoliver, can you please assign to Kesem?

Thank you.

**Comment by KesemSharabi** [comment]
Sorry for the late response.

I'm trying to get [Use R-powered Power BI visuals in Power BI](https://docs.microsoft.com/power-bi/desktop-r-powered-custom-visuals?toc=/powerbi-docs/developer/TOC.json&bc=/powerbi-docs/breadcrumb/toc.json) redirected to the [Power BI developer documentation](https://docs.microsoft.com/power-bi/developer/) and show the the developer breadcrumb (Docs / Power BI / Developer).

I'll fix the issue that this merge caused in another branch.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
#sign-off

**Comment by ktoliver** [comment]
This is fixed in the private repo https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/3044. The update should be live later today. We'll close this PR.

**Pull request closed without merging**
