### PR TITLE
Update learning-catalog-developer.md

### PR DESCRIPTION
**Pull request by heyrob**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@heyrob : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by heyrob** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@heyrob: I'm sorry - only the author of this article, @margoc, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Court72** [comment]
@margoc

Can you review the proposed changes? 

Note that line 27 is duplicated in the addition on line 26, "Best Practices for Managing Power BI Embedded Analytics for Multi-Tenant Deployments." 

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by MargoC — APPROVED** [review]

**Comment by MargoC** [comment]
#sign-off

**Pull request merged**
