### PR TITLE
FileExtension removal from CSV and XML

### PR DESCRIPTION
**Pull request by montanorx**
BUG: https://powerbi.visualstudio.com/Reach/_boards/board/t/Blitzar/Stories/?workitem=425226

Removing the ability to override/pass FileExtension through device info parameters in Cloud.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@montanorx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@montanorx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@montanorx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]
approved

**Comment by maggiesMSFT** [comment]
#sign-off
@montanorx

**Pull request merged**
