### PR TITLE
Updating R scripting docs about plotting device

### PR DESCRIPTION
**Pull request by otarb**
Adding note that only plotting to default device is supported

### CODE REVIEW

**Comment by PRMerger14** [comment]
@otarb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@otarb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@otarb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Thanks, @otarb! 
#sign-off

**Pull request merged**
