### PR TITLE
fix: powerbi-docs/desktop-analysis-services-tabular-data.md

### PR DESCRIPTION
**Pull request by nschonni**
Remove hidden character

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @nschonni - Could you clarify what update you made to the article? Thanks!

**Comment by nschonni** [comment]
There are unprintable characters in the file. In IDEs they show up as those "?" characters. I ended up batching most of these changes in another PR after since they don't diff easily on GitHub

**Comment by ktoliver** [comment]
@nschonni Thanks. I don't see the question mark character appearing in the live article or in diff, but something is causing a change in the diff view, and the PR looks OK to merge. Thanks for the explanation. We'll go ahead and merge the PR.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
#hold-off I'm going to check on this.

**Comment by ktoliver** [comment]
We've verified the fix in XML; looks good.

Thanks @nschonni

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Pull request merged**
