### PR TITLE
typo: Contributing docs

### PR DESCRIPTION
**Pull request by nschonni**
Fix typos and add code fence language on the contributing guides

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @mblythe, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author, @mblythe, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author, @mblythe, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@nschonni Per internal style guides, "markdown" is the label to use for the code fencing, and "palette" is correct for the spelling fix. I've made those changes, and I'm merging the PR.

Thanks for your contribution.

**Pull request merged**
