### PR TITLE
Redirect rewrite for GH compat

### PR DESCRIPTION
**Pull request by nschonni**
Rewrite the links from the redirect.json so you can navigate the docs on GH and in VS code

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Looks good, thanks, @nschonni! #sign-off

**Pull request merged**
