### PR TITLE
Scan mode off

### PR DESCRIPTION
**Pull request by tessahurr**
Added a note about turning scan mode and browse mode off

### CODE REVIEW

**Comment by PRMerger20** [comment]
@tessahurr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off for @davidiseminger , update from @tessahurr

**Pull request merged**
