### PR TITLE
typo: powerbi-docs/service-tutorial-connect-to-github.md

### PR DESCRIPTION
**Pull request by nschonni**
- dashboad -> dashboard
- navigaton -> navigation

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by rjagiewich** [comment]
Verified editorial corrections.

**Comment by PRMerger19** [comment]
@rjagiewich : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@rjagiewich : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Pull request merged**
