### PR TITLE
Update service-dashboards.md

### PR DESCRIPTION
**Pull request by hongju**
Add a space.
workspaceABC -> workspace ABC

### CODE REVIEW

**Comment by PRMerger7** [comment]
@hongju : Thanks for your contribution! The author(s) have been notified to review your proposed change. @maggieMSFT

**Comment by ktoliver** [comment]
Hi @maggiesmsft - Could you review the proposed changes? 

Also, when you have a chance, could you update the metadata `author` value to include the missing "s"? Automation is sending author notifications to a different GitHub user because of the typo. Thanks!

**Comment by PRMerger15** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change. @maggieMSFT

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
Hi, @ktoliver -- got it, thanks! Will update my alias.

**Pull request merged**
