### PR TITLE
Update paginated-reports-faq.md

### PR DESCRIPTION
**Pull request by Alonbaram**
SaaS embedding support

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Alonbaram : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by rkarlin** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@rkarlin, I'm sorry - only the author of this article, @maggiesMSFT, can sign off on your changes. But we do have an exception process:  You can ask the PR review team to review and merge it by sending mail to the techdocprs alias. Thanks.

**Comment by rkarlin** [comment]
Hi @jborsecnik I see that Maggie is OOF on vacation until the 5th. Is there anyone else who can approve Alon's changes?
thanks

**Comment by PRMerger19** [comment]
@Alonbaram : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Alonbaram** [comment]
@sign-off

**Comment by ktoliver** [comment]
#sign-off  per @Alonbaram

**Comment by PRMerger13** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Closing/reopening to trigger LCA check.

**Comment by ktoliver** [comment]
Reviewed. Merging per email with @davidiseminger and @rkarlin (contributor updated accordingly).

**Pull request merged**
