### PR TITLE
Further clarity on role requirements

### PR DESCRIPTION
**Pull request by greglow**
I've been at two sites lately that thought this meant the account needed to be a local server administrator on the Windows Server. I've added clarification. Also, in the UI, it calls it a Role not a permission, so I've adjusted that.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@greglow : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Thanks, @greglow ! Updating the article with your change.
#sign-off 
@arthiriyer

**Comment by PRMerger14** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @arthiriyer, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
