### PR TITLE
Updates for daylight savings fixes

### PR DESCRIPTION
**Pull request by mibruhje**
- we fixed the issue related to daylight savings; updating the doc to reflect this 
- updates ms.date

### CODE REVIEW

**Comment by PRMerger19** [comment]
@mibruhje : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mibruhje** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@mibruhje: I'm sorry - only the author of this article, @mihart, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ShannonLeavitt** [comment]
@mihart – Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by mihart — APPROVED** [review]

**Comment by mihart** [comment]
#sign-off

**Pull request merged**
