### PR TITLE
fix: powerbi-docs/paginated-reports-enter-data.md

### PR DESCRIPTION
**Pull request by nschonni**
Add code fence language and replace smart quotes

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're in the process of pulling this commit to the private repository so we can verify the updates on staging. We'll post a new private repo PR # shortly and then close this PR.

**Comment by PRMerger20** [comment]
@GitHubber17 : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Confirmed code fence identifier and corrections. Thanks for your contribution.

**Pull request merged**
