### PR TITLE
fix: powerbi-docs/desktop-report-themes.md

### PR DESCRIPTION
**Pull request by nschonni**
Add code fence languages and adjust indenting

### CODE REVIEW

**Comment by PRMerger18** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're in the process of pulling this commit to the private repository so we can verify the updates on staging. We'll post a new private repo PR # shortly and then close this PR.

**Comment by PRMerger6** [comment]
@GitHubber17 : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@GitHubber17 : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Confirmed code fence identifiers. Thanks

**Pull request merged**
