### PR TITLE
Update service-admin-portal.md

### PR DESCRIPTION
**Pull request by haydnr**
Needs https://powerbiblogscdn.azureedge.net/wp-content/uploads/2019/02/help-and-support-settings.png

### CODE REVIEW

**Comment by PRMerger7** [comment]
@haydnr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
