### PR TITLE
Updated scatter chart documentation

### PR DESCRIPTION
**Pull request by adilyalcin**
Added documentation for new marker size range scale feature.

### CODE REVIEW

**Comment by adilyalcin** [comment]
Please do not merge yet. Content is being reviewed.

**Comment by Court72** [comment]
@mihart

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
@adilyalcin and @msftrien -- can we sign off on this PR now?

**Review by mihart — APPROVED** [review]
made few edits

**Comment by mihart** [comment]
#sign-off

**Comment by mihart** [comment]
#sign-off

**Comment by mihart** [comment]
#hold-off

**Pull request merged**
