### PR TITLE
Removed scaling

### PR DESCRIPTION
**Pull request by Sujata994**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Sujata994 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Sujata994** [comment]
We aren't doing scaling any more based on feedback.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
#sign-off
again. Shouldn't this be an auto-merge? It's just a deletion.

**Comment by maggiesMSFT** [comment]
Oh, never mind, this is in the public repo

**Comment by maggiesMSFT** [comment]
making the change in the private repo, https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2260

**Pull request closed without merging**
