### PR TITLE
Update compare-report-server-service.md

### PR DESCRIPTION
**Pull request by ManuSQLGeek**
Removed R Visuals row in the comparison table.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@ManuSQLGeek : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ManuSQLGeek : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by ManuSQLGeek** [comment]
When does this gets updated on the page? Is there something I need to do? Sorry I am new to git and not sure what needs to be done.

**Comment by ktoliver** [comment]
@ManuSQLGeek Your pull request has been assigned to the article author for review.

**Comment by maggiesMSFT** [comment]
Hi, @ManuSQLGeek -- Thanks for your interest! Question: why are you suggesting that we remove this line about R visuals from the table? I have confirmed with the product team that it's still true.

**Comment by ManuSQLGeek** [comment]
Hi Maggies,

Thanks for checking with product team. I was confused because the Power BI Desktop Optimised for Report Server allowed me to create an R Visual. When I uploaded that report then it says "R visuals are currently disabled in your organisation" and the help link takes to the Power BI Service related R visuals page - https://docs.microsoft.com/en-us/power-bi/desktop-r-visuals. 

I am thinking one the following three actions should be helpful to clear this confusion or people wasting time to create the R visuals in the desktop and fianlly realising it doesn't work after uploading the report to the Report Server.

1. The desktop should not allow to create the R visual.
2. If it allows, the visual should be enabled in Power BI Report Server.
3. Worst case, the help link should be directed to a right page which contains related info.

Thanks,
Manu

**Comment by maggiesMSFT** [comment]
Oh, thanks for clarifying, @ManuSQLGeek! I get it now. OK, I'll update the language in the table to make that clearer.

**Pull request closed without merging**
