### PR TITLE
Update service-automate-power-bi-report-export.md

### PR DESCRIPTION
**Pull request by mohammedadnant**
Added row level security (RLS) procedure, this helps to apply RLS while exporting the report in PDF

### CODE REVIEW

**Comment by ktoliver** [comment]
Thanks @mohammedadnant. The article author has been asked to review your proposed update. Note that any images that are referenced in an article must exist in the repository; we can't merge in references to images that are hosted elsewhere. Could you either add the image files in this pull request or remove the image references? Thanks.

cc @maggiesMSFT

**Comment by mohammedadnant** [comment]
2 images
automate-report-scheduled-flow-rls_1
automate-report-scheduled-flow-rls_2

**Comment by mohammedadnant** [comment]
> 
> 
> Thanks @mohammedadnant. The article author has been asked to review your proposed update. Note that any images that are referenced in an article must exist in the repository; we can't merge in references to images that are hosted elsewhere. Could you either add the image files in this pull request or remove the image references? Thanks.
> 
> cc @maggiesMSFT

I have added the image in above comment, when I try to add in the media it says as below image
image
can you pls help to proceed further.

**Comment by maggiesMSFT** [comment]
Hi, @mohammedadnant  - just letting you know I'm working on this. I'll keep you posted.

**Comment by maggiesMSFT** [comment]
Hi, @mohammedadnant -- Thanks so much for your PR! We updated the article in an internal PR so I could add the images, and the changes are live:
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export

**Pull request closed without merging**
