### PR TITLE
fix: powerbi-docs/developer/embed-service-principal.md

### PR DESCRIPTION
**Pull request by nschonni**
Update closed br tags

### CODE REVIEW

**Comment by PRMerger17** [comment]
@nschonni : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by markingmyname** [comment]
@nschonni Not going to make the change on this as it works as expected.  

Thank you.

Please close this PR.

**Comment by nschonni** [comment]
A standalone closing `</br>` isn't valid HTML/Markdown, can you explain how it works as expected?

**Comment by PRMerger9** [comment]
@mgblythe : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@mgblythe : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Pull request merged**
