### PR TITLE
Update service-connect-cloud-data-sources.md

### PR DESCRIPTION
**Pull request by subisw**
customer wants these limitations to be part of the document as they have huge financial impact due to this issue

### CODE REVIEW

**Comment by Court72** [comment]
@davidiseminger

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by davidiseminger** [comment]
Hello @subisw -- are you a/the customer or an internal partner? The clarification will help how we potentially address the docs request.

**Comment by subisw** [comment]
I am Partner Technical Advisor working within Microsoft as FTE and reporting to Mueez Shariff (Mueezs).


Best Regards ,
Sumana Biswas | Partner Technical Advisor | Microsoft Power BI Support | Microsoft Corp
Office: +1 866-425-7701 Ex. 8981303 | ***@***.******@***.***> |
01:00 PM - 10:00 PM IST Mon - Fri
***@***.***

**Comment by davidiseminger** [comment]
Hello @subisw  -- I've re-written your request in a separate PR, to help it conform with our writing and clarity guidelines. That update will go live later today.

**Pull request closed without merging**
