### PR TITLE
Update report-builder-url-parameters.md

### PR DESCRIPTION
**Pull request by mroldx**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@mroldx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@maggiesMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
Hi, @mroldx -- Thanks for your suggestion! I'm checking and will sign off when I hear back. Responses may be delayed because of the pending holiday.

cc @Court72

**Comment by maggiesMSFT** [comment]
A speedy response!
#sign-off

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
again just to make sure
#sign-off

**Pull request merged**
