### PR TITLE
fix: powerbi-docs/developer/encrypt-credentials.md

### PR DESCRIPTION
**Pull request by nschonni**
Add code fence languages

### CODE REVIEW

**Comment by PRMerger13** [comment]
@nschonni : Thanks for your contribution! The author, @mahirdiab, has been notified to review your proposed change.

**Comment by MahirDiab** [comment]
@markingmyname please review and approve.

**Comment by ktoliver** [comment]
We're in the process of pulling this commit to the private repository so we can verify the updates on staging. We'll post a new private repo PR # shortly and then close this PR.

**Comment by PRMerger15** [comment]
@GitHubber17 : Thanks for your contribution! The author, @mahirdiab, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@MahirDiab - Would you review the proposed changes to add code fencing? Is "csharp" the correct code fence identifier to use for .NET examples? Thanks

**Comment by MahirDiab** [comment]
@GitHubber17, i think the PR need to be merged to master not live..
@markingmyname can you please take a look?

**Comment by nschonni** [comment]
@MahirDiab there is no `master` branch in this repo, maybe that is just in the private repo

**Comment by ktoliver** [comment]
Hi @MahirDiab - Unlike the private repository, the public powerbi-docs repository merges directly to live. 

CC @kfile

**Comment by nschonni** [comment]
I used `csharp` because of this comment
https://github.com/MicrosoftDocs/powerbi-docs/blame/d016ab54a259837177abd15f70602d4ad3c4dff3/powerbi-docs/developer/encrypt-credentials.md#L18
> See code example below how to encrypt the credentials in .NET.

**Comment by PRMerger13** [comment]
@markingmyname : Thanks for your contribution! The author, @mahirdiab, has been notified to review your proposed change.

**Pull request merged**
