### PR TITLE
Corrected distinction between SaaS and PaaS embedding following MS fi…

### PR DESCRIPTION
**Pull request by Alonbaram**
…eld complaints

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Alonbaram : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Pull request merged**
