### PR TITLE
chore: Remove testing files

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@nschonni : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@mgblythe : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Jak-MS : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Pull request merged**
