### PR TITLE
Update service-connect-to-project-online.md

### PR DESCRIPTION
**Pull request by ben-howard**
Users need to have the correct permissions to the Project Online tenant in order to access the OData feed.

### CODE REVIEW

**Comment by maggiesMSFT** [comment]
@SarinaJoan, were you notified that this gentleman created a PR for your article? IDK how this works yet, being the first day the public repo is turned on.

**Comment by maggiesMSFT** [comment]
@ben-howard, Thanks for your contribution to the Power BI documentation! The author, @sarinajoan, has been notified to review your proposed change.

**Comment by SarinaJoan** [comment]
#sign-off: @maggiesMSFT let me know if this works

**Comment by PRMerger13** [comment]
@ben-howard : Thanks for your contribution! The author, @SarinaJoan, has been notified to review your proposed change.

**Pull request merged**
