### PR TITLE
Update power-bi-query-caching.md

### PR DESCRIPTION
**Pull request by DaniilMaslyuk**
Included information on how long the cache persists, which I got from the comments.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@DaniilMaslyuk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Thanks so much for your contribution. I'm going to check with the developers and get back to you.

**Comment by PRMerger7** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
Please note that we can't merge to live. This request should be submitted to Master.

**Pull request closed without merging**
