### PR TITLE
Added Limitations of SPN

### PR DESCRIPTION
**Pull request by jayendranarumugam**
Updated the limitations with Gateway and data source for SPN

### CODE REVIEW

**Comment by PRMerger20** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Hi @jayendranarumugam, I'm checking your request with the development team and will respond shortly.

**Comment by KesemSharabi** [comment]
Hi @jayendranarumugam,

According to the development team you can add a service principal as a user to gateway datasources.

However, the service principal can’t be a gateway admin.

Perhaps you thought that you couldn’t do that, because it's not supported in the UI (it's only possible via the API).

Thanks,

**Comment by jayendranarumugam** [comment]
Hi @KesemSharabi , Thanks for getting back to me. I think spn now can be a gateway admin also, see this [official announcement](http://disq.us/p/299rc3q) and I tried to add the spn for the data source but couldn't able to get any link/API which you are referring here that is possible. could you please share the link here? that would be much helpful!

All I can see that this spn is possible only for [Analysis Service](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-tshoot#kerberos) and not the other datasoruces like sql , excel etc., which is on-prem

Thanks !
Jay

**Comment by PRMerger6** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Hi @jayendranarumugam,

I'm checking whether service principal can be a gateway admin or not, and will get back to you soon.

Thanks,

Kesem

**Comment by PRMerger9** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
