### PR TITLE
Update location of button

### PR DESCRIPTION
**Pull request by ChristopherMank**
Updated location of main action button for app update on production stage

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ChristopherMank : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Hi @ChristopherMank,

Thank you for spotting this and for your contribution.

**Comment by KesemSharabi** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
