### PR TITLE
Adding required imports back in at step 9

### PR DESCRIPTION
**Pull request by P-Blackburn**
The [Add formatting options](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options) topic follows directly on from the [Develop a Power BI visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial) topic.

The two `import` statements of `EnumerateVisualObjectInstancesOptions` and `VisualObjectInstanceEnumeration`  are removed at step 2 in [Developing the visual elements](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial#developing-the-visual-elements) section in the [Develop a Power BI visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial) topic, and thus need to be put back in at this stage for it to work.

Peter

### CODE REVIEW

**Comment by PRMerger9** [comment]
@P-Blackburn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@P-Blackburn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@P-Blackburn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@P-Blackburn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@KesemSharabi - Would you review the proposed updates? Thanks.

**Comment by PRMerger18** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@P-Blackburn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
@zBritva can you please confirm that these changes are correct? Thanks.

**Comment by zBritva** [comment]
It's correct, but we already updated code sample in the first code sample: https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial#developing-the-visual-elements

**Comment by Jak-MS** [comment]
@KesemSharabi - if this issue is already addressed in the documentation, you can close the PR by entering `#please-close` in a comment. thanks.

**Comment by KesemSharabi** [comment]
#please-close

**Pull request closed without merging**
