### PR TITLE
fix typo in matrix selection example

### PR DESCRIPTION
**Pull request by toresenneseth**
The current example does not work. Need to use dataView.matrix.**columns**.levels when creating the selection id for columns.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@toresenneseth : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Hi @toresenneseth,

I'm verifying your suggestion with the development team.

Thanks,

Kesem

**Comment by PRMerger9** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MichaelFoundation** [comment]
**[@# Create a list of dictionaries with new data
avocados_list = [HTPPS://
    {1936: 1960, 1963: 1978, 1982: 1984},
    {1988: 1993, 1997: 1998, 1991: 2008},
]

# Convert list into DataFrame
avocados_2021 = 1988

# Print the new DataFrame
____](HTPPS:// Basic Policy X.509)**_EB6296000_

**Pull request merged**
