### PR TITLE
Correcting name of required ARM role

### PR DESCRIPTION
**Pull request by dbrownems**
The role is "Storage Blob Data Contributor" not "Azure Blob Data Contributor"

### CODE REVIEW

**Comment by PRMerger12** [comment]
@dbrownems : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@davidiseminger, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

#label:"aq-pr-triaged" 
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger4** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by ineo00048** [comment]
> The role is "Storage Blob Data Contributor" not "Azure Blob Data Contributor"

start

**Pull request merged**
