### PR TITLE
Update desktop-connect-bigquery.md

### PR DESCRIPTION
**Pull request by ananth11**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ananth11 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Hi, @ananth11 -- the author will be getting in touch with you. Thanks for your feedback!

**Comment by PRMerger6** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by davidiseminger — APPROVED** [review]
Updated the date, and cleaned up the wording

**Comment by PRMerger7** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
