### PR TITLE
Update OS requirement to Windows 10 / Server 2016

### PR DESCRIPTION
**Pull request by tnclark8012**
Support for Windows 8.1 ends 1/31/2024 after a year of notice.

### CODE REVIEW

**Comment by tnclark8012** [comment]
We should wait to publish this until 1/31/2024

**Comment by Jak-MS** [comment]
@davidiseminger 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
Don't sign off until 1/31/2024

**Comment by tnclark8012** [comment]
@davidiseminger today's the day :) This is ready to merge

**Comment by davidiseminger** [comment]
Indeed it is! Thanks @tnclark8012 !

#sign-off

**Pull request merged**
