### PR TITLE
Added link to PubNub doc about whitelisting outbound traffic

### PR DESCRIPTION
**Pull request by eklavyamirani**
Added instructions to clarify that if the customers have a locked firewall, they would need to allow outbound traffic to PubNub to be able to use the datasets.

Edit: (Adding some more context.)
I am on the PowerBI Team that owns Push Datasets. We discussed this internally and wanted to point out that if the customer locks down their environment to only a set of allowed outgoing traffic, then they should be aware that the web client calls into PubNub to get data and they need to add PubNub urls to their allowed list of outgoing traffic.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@eklavyamirani : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@davidiseminger - Could you review the proposed updates? Note that in Microsoft Docs content, "whitelist" in text should be replaced with "allow list" (noun)/"add to an allow list".

**Comment by maikelson** [comment]
@davidiseminger FYI, @eklavyamirani and I already discussed this change and we both agree is the best way to go based on the latest JEDI work we are looking at.

**Comment by ktoliver** [comment]
The PR review team will move this commit to the private repository. We'll post the PR number here and then close this PR.

**Comment by ktoliver** [comment]
The update submitted in this PR has been moved to the private repo. The contributor will continue to be associated with the update. The private repo PR is https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/3661. We'll close this PR. Thanks.

**Comment by maikelson** [comment]
@ktoliver and @davidiseminger: Can you tell us why this didn't get published? @eklavyamirani and I are wondering if there's anything we are missing to make this happen. In see the language change ask and I assume we are fine with that. Can you let us know so we can re-open this and publish? Thanks!

**Comment by maikelson** [comment]
#sign-off

**Pull request closed without merging**
