### PR TITLE
Update paginated-reports-odbc-support.md

### PR DESCRIPTION
**Pull request by bradsy1**
Update to include another known issue.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@bradsy1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by PRMerger15** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
