### PR TITLE
Update service-gateway-onprem.md

### PR DESCRIPTION
**Pull request by andikrueger**
Added line break in Next steps

### CODE REVIEW

**Comment by PRMerger18** [comment]
@andikrueger : Thanks for your contribution! The author, @mgblythe, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author, @mgblythe, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Merging line spacing fix

**Comment by mgblythe** [comment]
#sign-off. Thanks @andikrueger

**Pull request merged**
