### PR TITLE
Update service-encryption-customer-managed-keys.md

### PR DESCRIPTION
**Pull request by DavidMagarMS**
urgent update due to customer feedback that creates misunderstanding

### CODE REVIEW

**Comment by PRMerger20** [comment]
@DavidMagarMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@DavidMagarMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@tfosmark

**Comment by ktoliver** [comment]
Hi @DavidMagarMS -- This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make future content updates in the private repo? Thank you!

**Pull request merged**
