### PR TITLE
Added Azure Log Analytics connections for workspace administrators

### PR DESCRIPTION
**Pull request by soheildataviz**
Azure Log Analytics connections for workspace administrators is missing from the document.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@paulinbar 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.



#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by soheildataviz** [comment]
Any updates on this? I see the changes haven't gone through yet!

**Comment by Court72** [comment]
@paulinbar

Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?

Thanks!

**Comment by paulinbar** [comment]
Hi @soheildataviz, I am closing this PR because I opened another PR for this information. The review link is below. It should be published on Monday 24 October around 15:30 Redmond time.

https://review.learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-audit-usage?branch=pr-en-us-8688#azure-log-analytics-connections-for-workspace-administrators

**Pull request closed without merging**
