### PR TITLE
Update power-bi-visualizations-arcgis.md

### PR DESCRIPTION
**Pull request by flossyfolsom**
Proposed changes from Esri ArcGIS for Power BI team. Please contact me with any questions.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@flossyfolsom : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@mihart 

Can you review this PR?

Note that due to the number and nature of the changes, if you approve, these will need to be moved to (or resubmitted  via) the private repo. Let us know if you'd like assistance with that. 

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by JasonWHowell** [comment]
Close / Open to trigger a build.

**Comment by Jak-MS** [comment]
@JasonWHowell @mihart - it's good to have validation working, but even if those warning issues are addressed,  this PR is too large for the public repo.  If you approve the content changes, the commits will need to be moved to the private repo so we can review with the staging tools, etc. Thanks.

**Comment by PRMerger7** [comment]
@flossyfolsom : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@flossyfolsom : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by davidiseminger** [comment]
Hello all -- these changes are too large for a public repo. @flossyfolsom  - are you an ArcGIS employee? If so, please let us know and we can work together to get this significant requested update to the article addressed. We would initiate that process over email.

**Comment by flossyfolsom** [comment]
@davidiseminger Yes. I am an Esri/ArcGIS employee. Please email me rfolsom@esri.com

**Comment by mihart** [comment]
Hi @flossyfolsom @davidiseminger , @msftrien 
There are 2 articles for ArcGIS.  

1. https://docs.microsoft.com/en-us/power-bi/consumer/end-user-arcgis is for folks who are interacting with an ArcGIS map that has been created by someone else. I updated that article using your Word doc this past spring. 
 
2. https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis is for folks who are creating ArcGIS maps.  It appears that this doc was not updated. I apologize for the oversight and have reactivated the thread from this past spring and linked it to this PR.  The edits you have made in this PR will make the update much easier, thank you!

- Michele

**Comment by flossyfolsom** [comment]
> Hi @flossyfolsom @davidiseminger , @msftrien There are 2 articles for ArcGIS.
> 
> 1. https://docs.microsoft.com/en-us/power-bi/consumer/end-user-arcgis is for folks who are interacting with an ArcGIS map that has been created by someone else. I updated that article using your Word doc this past spring.
> 2. https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis is for folks who are creating ArcGIS maps.  It appears that this doc was not updated. I apologize for the oversight and have reactivated the thread from this past spring and linked it to this PR.  The edits you have made in this PR will make the update much easier, thank you!
> 
> * Michele

Hi, @mihart I was waiting to see the outcome of this page before tackling the https://docs.microsoft.com/en-us/power-bi/consumer/end-user-arcgis topic. I'll tackle that now! MANY THANKS!

**Comment by maggiesMSFT** [comment]
Hi, @flossyfolsom 
@msftrien 
@mihart 
We're assigning this to a vendor and handing off the updated Word doc and image files. I'll let you know when it's ready.
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @flossyfolsom @msftrien @mihart --
The vendor has completed converting the Word doc to markdown and adding all the images:
https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/8692
Changes should be live tomorrow. At that point, it'll be much easier for you to update in the public repo.
Thanks!

**Comment by flossyfolsom** [comment]
@maggiesMSFT Great news! We're so happy to have this new path forward to work with you.

**Comment by maggiesMSFT** [comment]
@flossyfolsom -- 
And we're so happy to have your collaboration. Thanks for helping us keep the docs up to date!

**Pull request closed without merging**
