### PR TITLE
Update service-dataflows-connect-azure-data-lake-storage-gen2.md

### PR DESCRIPTION
**Pull request by AldrinL**
According to SR_120052826001249, if the current user did not create the storage account, and want to use an existing account, then additional permission is required.added this information.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@AldrinL : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Admin note: If the PR is approved, remove the locale from the docs.microsoft.com URLs before merging. The PR review team can do this.

**Comment by PRMerger19** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
