### PR TITLE
Provide link to page showing how to find your PBI region

### PR DESCRIPTION
**Pull request by simonsabin**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@simonsabin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
Thanks, @simonsabin ! Good idea, adding the link. 
#sign-off

**Comment by PRMerger12** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @davidiseminger, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
