### PR TITLE
Formatting list inside table cell

### PR DESCRIPTION
**Pull request by bgribaudo**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@bgribaudo : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@maggiesMSFT : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off for @davidiseminger -- formatting improvement.

**Comment by PRMerger17** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @davidiseminger, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
