### PR TITLE
typo: Expresssions -> Expressions

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @jtarquino, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@TrishaMc : Thanks for your contribution! The author, @jtarquino, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@TrishaMc : Thanks for your contribution! The author, @jtarquino, has been notified to review your proposed change.

**Comment by TrishaMc** [comment]
Editorial fix confirmed.

**Pull request merged**
