### PR TITLE
Update whitepaper-azure-b2b-power-bi.md

### PR DESCRIPTION
**Pull request by Khairunj**
updated the document for more gender specific
There is also a user name "Lucy" on the page that we need to fix later once we have approved list of gender neutral name.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Khairunj : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by Khairunj** [comment]
WTD: Proposing the changes as part to the write the docs gender inclusive subject

**Comment by PRMerger6** [comment]
@SyntaxC4 : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@SyntaxC4 : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Pull request merged**
