### PR TITLE
Sharing gives access to the dataset

### PR DESCRIPTION
**Pull request by eugman**
When sharing a dashboard, doing so gives access to the underlying reports and datasets. Even though the dataset doesn't show up in the user's workspace, there are still ways to access it, such as Analyze in Excel.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@eugman : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@eugman : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@rjagiewich : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mgblythe : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@GitHubber17 : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
HI, @eugman -- thanks for your comment and sorry for the delay. Took me a while to get to the answer. I'm going to close your PR because I'm going to update the article with this text:
- No one can see or download the dataset, but they can access the dataset directly using the Analyze in Excel feature. An admin can restrict people’s ability to use Analyze in Excel by restricting the ability for everyone in a group. However, the restriction is for everyone in that group for every workspace the group belongs to.
Thanks for asking!

**Pull request closed without merging**
