### PR TITLE
Update service-security-using-microsoft-cloud-app-security-controls.md

### PR DESCRIPTION
**Pull request by dankad256**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@dankad256 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by paulinbar — APPROVED** [review]
Looks fine

**Comment by paulinbar** [comment]
#sign-off

**Comment by ktoliver** [comment]
The update that's submitted in this pull request is already in master, but with slightly different wording (thus, a merge conflict is generated):

image

We'll close this pull request as a duplicate. The previously merged text should be live today. Thanks!

**Pull request closed without merging**
