### PR TITLE
typo: powerbi-docs/desktop-calculated-tables.md

### PR DESCRIPTION
**Pull request by nschonni**
Soutwest -> Southwest

### CODE REVIEW

**Comment by PRMerger6** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Merging typo fix.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Pull request merged**
