### PR TITLE
fix: powerbi-docs/service-gateway-personal-mode.md

### PR DESCRIPTION
**Pull request by nschonni**
Add code fence language and remove extra backticks

### CODE REVIEW

**Comment by PRMerger8** [comment]
@nschonni : Thanks for your contribution! The author, @mgblythe, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're in the process of pulling this commit to the private repository so we can verify the updates on staging. We'll post a new private repo PR # shortly and then close this PR.

**Comment by PRMerger17** [comment]
@GitHubber17 : Thanks for your contribution! The author, @mgblythe, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Confirmed code fence identifier and syntax correction. Thanks for your contribution.

**Pull request merged**
