### PR TITLE
powerbi desktop - updated desktop connect azure CI aricle to add link…

### PR DESCRIPTION
**Pull request by bandersmsft**
… to video

### CODE REVIEW

**Comment by PRMerger6** [comment]
@bandersmsft : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Hi @bandersmsft - we'll assign this to the listed author @davidiseminger for review.

In the future, can you submit article changes to the private repository instead? (powerbi-docs-pr)

Thanks,

***
Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

After you review staging and fix all validation issues, you can tag an author for review or add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Comment by bandersmsft** [comment]
@jak-ms will do. Sorry, I mistakenly cloned the public repo! I'll be sure to get the private repo next time.

**Comment by PRMerger9** [comment]
@bandersmsft : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@mgblythe : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@Jak-MS : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@mgblythe @davidiseminger - can you provide specific guidance for this PR. 

- `#sign-off` if it's ready to merge
- `#hold-off` if it requires changes before it's ready for sign off
- `#please-close` - if these changes aren't going to be merged

Thanks!

**Comment by PRMerger9** [comment]
@mgblythe : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by davidiseminger** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@davidiseminger : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Pull request merged**
