### PR TITLE
Update paginated-reports-faq.md to have considerations section

### PR DESCRIPTION
**Pull request by thisisagithubaccountforwork**
- Add section for considerations
- add glob issue to the considerations section

### CODE REVIEW

**Comment by PRMerger8** [comment]
@thisisagithubaccountforwork : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @maggiesMSFT - Could you review the proposed updates? The reference to future updates and functionality should be removed before the PR is merged. Thanks.

**Comment by maggiesMSFT** [comment]
Hi, @ktoliver -- yes, thx. I'm checking with the PM to see if he wants the change. I am irked that I have no idea who this is. 
@thisisagithubaccountforwork -- please contact me.

**Comment by thisisagithubaccountforwork** [comment]
Uh sorry it won’t let me change my display name. Still trying to fix it up. I made this like 5 years ago.

**Comment by PRMerger16** [comment]
@thisisagithubaccountforwork : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
@thisisagithubaccountforwork & @ktoliver -- closing this, will recreate in private repo. @thisisagithubaccountforwork , sending more details offline.

**Comment by thisisagithubaccountforwork** [comment]
Thanks

**Pull request closed without merging**
