### PR TITLE
Update office-store.md

### PR DESCRIPTION
**Pull request by sranins**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@sranins : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@sranins : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by markingmyname** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@sranins : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Pull request merged**
