### PR TITLE
Update deployment-pipelines-get-started-3rdparty-visual.md

### PR DESCRIPTION
**Pull request by mohammedadnant**
Update deployment pipelines when we use for reports which contains 3rd party visual and compare 2 environment it will show as 2 different report, so you cannot use deployment in this type of deployment, you have to use regular manual method to deploy the reports

### CODE REVIEW

**Comment by PRMerger14** [comment]
@mohammedadnant : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Hi @mohammedadnant,

Thanks for your comments - I'm checking them with the development team and the PM.

Kesem

**Comment by KesemSharabi** [comment]
Hi @mohammedadnant,

This doesn't seem like an expected behavior. We'll investigate further to see if it's a bug.

Just to confirm - you have a report with a third party visual, and after deployment, when you're using the compare function there's a difference between the report in the source stage and the target stage?

Thanks,

Kesem

**Comment by mohammedadnant** [comment]
Hi @Kesem,

Thanks for your reply, I have worked with Acterys Visual, there we need to manually feed the API key manually for each environment UAT/PROD, under format tool of that visual.

By doing this deployment pipeline thinks this is 2 separate report, that's why I have highlighted here.
Hope it is clear now.

Thanks & Regards,
Mohammed Adnan

**Comment by mohammedadnant** [comment]
> 
> 
> Hi @mohammedadnant,
> 
> This doesn't seem like an expected behavior. We'll investigate further to see if it's a bug.
> 
> Just to confirm - you have a report with a third party visual, and after deployment, when you're using the compare function there's a difference between the report in the source stage and the target stage?
> 
> Thanks,
> 
> Kesem

Hi Kesem, Example in Acterys visual we need to update the API detail to write back to the database, this option is available under format option of the visual, so for 2 environment UAT/PROD we need to enter 2 different API details, in this deployment pipeline thinks these 2 are different file, hope this helps.. pls let me know Regards, Adnan

**Comment by KesemSharabi** [comment]
Hi @mohammedadnant,

I can confirm that this is a bug and that the documentation doesn't need to be changrd.

Hopefully the development team will fix this shortly.

Thanks,

Kesem

**Pull request closed without merging**
