### PR TITLE
No changes created - more information required

### PR DESCRIPTION
**Pull request by loryanstrant**
Please expand as the setting and setting name create a double negative, which this document offers no explanation on how to address.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@loryanstrant : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by loryanstrant** [comment]
Sorry why was this closed? The doc hasn't been updated and is therefore no clearer about providing an explanation.

**Comment by paulinbar** [comment]
Hi @loryanstrant, I think this must have been closed by an automatic process, my apologies. I am on the docs team that maintains that article and was out for most of the month due to illness, so I didn't see what was going on. In any event, I am in the process of tracking down the product manager for that feature to get a more informative explanation of the switch than what you see in the UI. As for the double negative resulting from the combination of the switch name and the toggle, I will pass that feedback along. Unfortunately the doc writers are generally not part of the loop that creates the UI design and text, and we just have to deal with what's there.  
Thanks for calling my attention to this issue. Hopefully I'll be able to provide an update soon.

**Comment by paulinbar** [comment]
Hi @loryanstrant,
I am closing PR and opening your question as a Git hub issue (https://github.com/MicrosoftDocs/powerbi-docs/issues/4015), which is the usual channel for issues such as the one that you raised.
Thanks.

**Comment by loryanstrant** [comment]
Thanks, sorry I don't know why I didn't do that myself!
I think I was in auto-PR-pilot mode.

**Pull request closed without merging**
