### PR TITLE
Added details of Security Update in PBI Desktop Oct 2017

### PR DESCRIPTION
**Pull request by pasundar**
@lishibo

### CODE REVIEW

**Comment by PRMerger6** [comment]
@pasundar : Thanks for your contribution! The author, @jtarquino, has been notified to review your proposed change.

**Comment by lishibo** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@lishibo: I'm sorry - only the author of this article, @jtarquino, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jtarquino** [comment]
#sign-off

**Comment by lishibo** [comment]
@maggiesMSFT, could you help merge the PR?

**Comment by maggiesMSFT** [comment]
@lishibo - yes, I can. @pasundar , thanks for updating the article! In the future, can I ask you to create PRs in the private repo, powerbi-docs-pr, rather than the public one, powerbi-docs? The public repo is for... the public. I'll send you a link that explains how to. It's basically the same work flow.
thanks -- maggie

**Comment by pasundar** [comment]
@maggiesMSFT Yeah sure

**Pull request merged**
