### PR TITLE
Update service-desktop-files.md

### PR DESCRIPTION
**Pull request by valkyrienc**
Added info about using a Sync folder to access PBIXs stored in SharePoint (line 29)

### CODE REVIEW

**Comment by PRMerger13** [comment]
@valkyrienc : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Admin note: If the PR is approved, the locale needs to be removed from the microsoft.com URL before merging. The PR review team can do this.

**Comment by PRMerger19** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidiseminger** [comment]
Great - thanks @ktoliver - the changes look good to me, but please remove that en-us from the link. 

#sign-off

**Comment by PRMerger20** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
