### PR TITLE
Doc update for unsupported Interactive Exports for Private Links

### PR DESCRIPTION
**Pull request by ksgaipal**
Updating documentation for unsupported Interactive exports as PDF or PowerPoint when Azure Private Link is enabled

### CODE REVIEW

**Comment by PRMerger10** [comment]
@ksgaipal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by mibruhje** [comment]
@ksgaipal Can you add "in Power BI" at the end of this point and a period? Just to make it consistent with the other bullet points in the section.

**Comment by PRMerger12** [comment]
@ksgaipal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ksgaipal** [comment]
> 

Added

**Review by mibruhje — APPROVED** [review]
Looks good to me!

**Comment by ktoliver** [comment]
Merging with PM approval; thanks for the review @mibruhje.

**Pull request merged**
