### PR TITLE
Format Reporting Services LoadTest link

### PR DESCRIPTION
**Pull request by nschonni**
Nothing wrong with the old one, just got a false positive with link crawling and thought this also makes sense

### CODE REVIEW

**Comment by PRMerger6** [comment]
@nschonni : Thanks for your contribution! The author, @parthsha, has been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@nschonni : Thanks for your contribution! The author, @parthsha, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Thanks, @nschonni. I'll accept the change for @parthsha.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @parthsha, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
