### PR TITLE
Task_242475_1

### PR DESCRIPTION
**Pull request by chamukallem-msft**
First batch of files with ALT text.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@chamukallem-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@chamukallem-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@chamukallem-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chamukallem-msft** [comment]
@maggiesMSFT

**Pull request closed without merging**
