### PR TITLE
Add info about Power BI add-in not supporting WIP

### PR DESCRIPTION
**Pull request by petewu100**
Added information about the Power BI add-in not being supported in WIP enabled presentations.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@petewu100 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@petewu100 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@paulinbar 

Can you review this PR?

fyi, the addition of the non-repo image will need to be removed. 

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger18** [comment]
@petewu100 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@petewu100 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by JasonWHowell** [comment]
Close / Open to trigger a build.

**Comment by PRMerger12** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Image File | This PR added or updated an image file(s).

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Image File | This PR added or updated an image file(s).

**Pull request closed without merging**
