### PR TITLE
Update dataflows-azure-data-lake-storage-integration.md

### PR DESCRIPTION
**Pull request by kerski**
Based on my experience on May 24th, 2022 and reading the top search result to an Access Denied issue: https://community.powerbi.com/t5/Community-Blog/Connecting-to-an-Azure-Data-Lake-Gen-2-at-a-Power-BI-Workspace/ba-p/1412362   ... I am submitting an update to the prerequisites.  Thank you.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@kerski : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@davidiseminger 

Can you review the proposed changes? Note that the "Note:" on line 31 needs to be converted to a Markdown callout before merge.

*IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Comment by PRMerger13** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by davidiseminger** [comment]
Thanks for the contributions @kerski - I made a few stylistic changes as required and have merged. Thanks again!

**Comment by kerski** [comment]
You're welcome.

**Pull request merged**
