### PR TITLE
Add link to admin portal page

### PR DESCRIPTION
**Pull request by verargulla**

### CODE REVIEW

**Comment by PRMerger3** [comment]
@verargulla : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@davidiseminger 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by davidiseminger** [comment]
Great addition - thanks!

#sign-off

**Comment by verargulla** [comment]
Thank you! My first github commit. :)

**Pull request merged**
