### PR TITLE
Update title and edit for wording

### PR DESCRIPTION
**Pull request by MargoC**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@MargoC : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MargoC** [comment]
@maggiesMSFT minor tweaks.

**Comment by ktoliver** [comment]
Hi @Margoc - Members of the content team should work in the private repository for advanced quality validations and staging (you also can sign off directly in the private repo). To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. We’ll leave this PR for review in the public repo, but would you make future article updates in the private repo?  Thanks!

**Comment by MargoC** [comment]
@ktoliver , for all of the Dynamics 365 and Power Platform repos, when I start to edit as a Microsoft employee, I am automatically flipped to the private repo. Is there a reason that hasn't been implemented for the rest of the repos? Could it be? (It may be a rights thing, but remembering which repo I have which rights in can be painful, because I work across so many of them).

**Comment by maggiesMSFT** [comment]
Hi, @MargoC -- nope, our repo isn't set up that way. Don't know why. It would make life easier for all of us. Did you start from the pencil icon, looking at a live article? If so I can share a tool with you that will make it so you go automatically to the private repo. Only in Chrome, so far.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
OK, @MargoC I merged this PR. No worries.

**Pull request merged**
