### PR TITLE
Typos fixes for double words

### PR DESCRIPTION
**Pull request by nschonni**
Ran vale and cleaned up some repeating words

### CODE REVIEW

**Comment by PRMerger13** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@nschonni : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off
Signing off because articles belong to several different writers, all changes look great.

**Comment by PRMerger13** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @davidiseminger, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
