### PR TITLE
calling out that secure embed does not work with sp on prem

### PR DESCRIPTION
**Pull request by andreea-s**
this issue is hard to investigate and keeps coming back. calling it out in the docs to save future on call engineers some trouble.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@andreea-s : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by andreea-s** [comment]
will there be any validation for the links that I added? forgot to preview the file to make sure it looks right.

**Comment by PRMerger19** [comment]
@andreea-s : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
> will there be any validation for the links that I added? forgot to preview the file to make sure it looks right.

Hi @andreea-s Link validation occurs only in the private repository. To have the links validated, close this PR and re-create the PR in the private repo (powerbi-docs-pr). Microsoft authors and contributors should make content contributions through the private repository so the content can be staged and validated by the current validation rules.

**Comment by maggiesMSFT** [comment]
Hi, @andreea-s --
I'm closing this PR and making the change in a PR in the private repo, https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/3245

**Pull request closed without merging**
