### PR TITLE
Quick-insights-in-import-rls.md

### PR DESCRIPTION
**Pull request by mohammedadnant**
Role level security (RLS) is not supported by Quick Insights even in import mode

### CODE REVIEW

**Comment by PRMerger7** [comment]
@mohammedadnant : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
Thanks, @mohammedadnant -- looks good! I've signed off. Change should be live later today or tomorrow.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
@ktoliver -- yes, thanks!
#sign-off

**Pull request merged**
