### PR TITLE
Update service-publish-to-web.md

### PR DESCRIPTION
**Pull request by jayendranarumugam**
As there is already a hyperlink available to the user owns data, Again the same duplicate link is provided. So removing the duplicate links

### CODE REVIEW

**Comment by PRMerger13** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @jayendranarumugam - It looks like your branch is out of date with the base branch. Could you update your branch? Then we'll merge the PR. Thanks.

**Comment by PRMerger13** [comment]
@jayendranarumugam : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jayendranarumugam** [comment]
Hi @ktoliver I've updated the branch

**Comment by ktoliver** [comment]
@jayendranarumugam Thanks!

**Pull request merged**
