### PR TITLE
Aligning the gx64krb5 SSO Kerberos for SAP BW doc with the other docs

### PR DESCRIPTION
**Pull request by vleslief-ms**
Other docs located here:
https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-kerberos#complete-data-source-specific-configuration-steps
https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-kerberos-sap-bw-gx64krb

Connections with gx64krb5 are still possible, but unsupported.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@vleslief-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by arthiriyer — APPROVED** [review]

**Comment by PRMerger4** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @arthiriyer, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger16** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Hi, @vleslief-ms -- I'm going to revert your changes. It turns out you were editing an out-of-date version of the article. I need to figure out why that is. But I've check with the article owner, who says the version that is currently live is correct as is. Thanks!

**Pull request merged**
