### PR TITLE
Updating Limitations for Publish to Web - Q&A visuals

### PR DESCRIPTION
**Pull request by ravisrao**
Q&A visuals are not supported for publish to web. Updating the public docs accordingly.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@ravisrao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ravisrao** [comment]
Hi Team,

I have updated the public docs for P2W regarding a limitation.
Q&A visuals are not supported for P2W.

Please find attached an email thread regarding the confirmation that the feature isn’t supported..

Thanks,
Ravi

**Review by maggiesMSFT — APPROVED** [review]
approved

**Comment by maggiesMSFT** [comment]
#sign-off

**Pull request merged**
