### PR TITLE
fix: powerbi-docs/developer/walkthrough-push-data-add-rows.md

### PR DESCRIPTION
**Pull request by nschonni**
Add code fence languages

### CODE REVIEW

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@nschonni : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
We're in the process of pulling this commit to the private repository so we can verify the updates on staging. We'll post a new private repo PR # shortly and then close this PR.

**Comment by PRMerger10** [comment]
@GitHubber17 : Thanks for your contribution! The author, @markingmyname, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
Confirmed code fence identifiers. Thanks for your contribution.

**Pull request merged**
