### PR TITLE
Update visual-project-structure.md

### PR DESCRIPTION
**Pull request by hongju**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@hongju : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Hi @hongju,

Thank you for fixing this typo!

#sign-off

**Comment by PRMerger8** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Hi, @hongju -- thanks for catching that typo!
#sign-off

**Pull request merged**
