### PR TITLE
Update end-user-powerpoint.md

### PR DESCRIPTION
**Pull request by OrrinEdenfield**
Added additional limitation that PG (@JonHeide ) has confirmed.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@OrrinEdenfield : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by elimuhub7407 — APPROVED** [review]

**Comment by ktoliver** [comment]
@elimuhub7407 Thanks for your SME review.

@mihart Could you review/sign off for the content team?

Thanks!

**Comment by maggiesMSFT** [comment]
Thanks so much, @OrrinEdenfield @ We've updated this article, and the one about exporting to PDF, based on your suggestion!

**Pull request closed without merging**
