### PR TITLE
Update Theme Repo Link in Docs

### LINKED ISSUE #3402: Power BI Theme Template repository link is outdated and should be updated.
Section:
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#json-example-files

Documentation is pointing to an inactive repository, and the link should be updated to point to https://github.com/MattRudy/PowerBI-ThemeTemplates#readme

I'll submit a PR for this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

### PR DESCRIPTION
**Pull request by MattRudy**
Closes #3402

### CODE REVIEW

**Comment by PRMerger16** [comment]
@MattRudy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger18** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Thanks, @MattRudy !
#sign-off

**Pull request merged**
