### PR TITLE
Update Note for getting around firefox certificate blocking

### PR DESCRIPTION
**Pull request by niwsa**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@niwsa : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
@uve - can you please confirm that this change is correct?

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
Hi @niwsa 

I asked @uve to review your suggestion. He'll be back next week and will let me know if we can add this to our documentation.

Thanks,

Kesem

**Comment by PRMerger6** [comment]
@KesemSharabi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@KesemSharabi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
@niwsa, 

Thank you for your contribution. I slightly edited the text  and will approve the PR.

**Comment by KesemSharabi** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@KesemSharabi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@tfosmark

**Pull request merged**
