### PR TITLE
Fixes @logExceptions decorator for debugging

### PR DESCRIPTION
**Pull request by LinqLover**
Uses solution by @CleberDSantos described in https://github.com/microsoft/PowerBI-visuals/issues/221#issuecomment-335271888. For some reason, Function is not a valid generic type.

Closes microsoft/PowerBI-visuals#221 and also closes microsoft/PowerBI-visuals#434. I originally requested this in microsoft/PowerBI-visuals#591.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@LinqLover : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by KesemSharabi** [comment]
@helen508light and @uve - can you please take a look at this comment?

**Comment by KesemSharabi** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
