### PR TITLE
Update PBIRS release cadence

### PR DESCRIPTION
**Pull request by sqlchicken**
Updated portion that says PBIRS updates 4x/year to the updated release cadence announced https://powerbi.microsoft.com/en-us/blog/power-bi-report-server-release-timing-update/

### CODE REVIEW

**Comment by PRMerger15** [comment]
@sqlchicken : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Thanks for the great catch! I'm signing off so it can get merged.
#sign-off

**Comment by PRMerger9** [comment]
You can only sign off in the main PR conversation, not in review comments. In general, the creator of the PR should sign off, not the tech reviewer.

**Pull request merged**
