### PR TITLE
Specify python limitation in this doc

### PR DESCRIPTION
**Pull request by ibarrau**
I have found a post in power bi community of a user asking for python in publish to web and the doc doesn't specify it. It does specify R. I think it's a good idea to include it in the same sentence.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@ibarrau : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @maggiesMSFT Could you review this pull request? Thanks!

**Review by maggiesMSFT — APPROVED** [review]
approved

**Comment by maggiesMSFT** [comment]
Thanks, @ibarrau ! Good suggestion. Done.
Hi, @ktoliver - yes, I was just confirming. Thanks!
@sign-off

**Comment by ktoliver** [comment]
Thanks!

**Pull request merged**
