### PR TITLE
Spelling fixes and update to Desktop Data Sources

### PR DESCRIPTION
**Pull request by modery**
Correcting a few spellings
Also updating Desktop Data Source with one rename and updated screenshots

### CODE REVIEW

**Comment by PRMerger13** [comment]
@modery : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@modery Thanks for your contribution to the documentation.

I can confirm all updates except for a few . . .

@davidiseminger Could you review the revisions in **/connect-data/desktop-data-sources.md** and the image files?

@margoc Could you review the revisions in your articles:

**/learning-catalog/learning-catalog-bdm.md  
/learning-catalog/learning-catalog-presales.md**  

Thanks.

**Review by maggiesMSFT — APPROVED** [review]

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
Hi, @modery -- thanks for making all those updates!

**Comment by ktoliver** [comment]
Thanks, all.

**Pull request merged**
