### PR TITLE
Adding Aliases for PowerShell cmdlets.

### PR DESCRIPTION
**Pull request by cporteou**
Added Aliases to PowerShell cmdlets. Some of these are simpler for people getting started with the module

### CODE REVIEW

**Comment by PRMerger15** [comment]
@cporteou : Thanks for your contribution! The author, @mgblythe, has been notified to review your proposed change.

**Comment by PRMerger8** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by mgblythe** [comment]
Thanks @cporteou! @CodeCyclone -- can you review this PR, then I will sign off and we can get it merged.

**Comment by CodeCyclone** [comment]
Looks good you can merge this

**Comment by PRMerger6** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by mgblythe** [comment]
@cporteou -- I ended up creating a PR for this in the private repo: https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/1306. If you want to make other doc updates, let me know. Thanks for the input!

**Pull request merged**
