### PR TITLE
Update projects-overview.md

### PR DESCRIPTION
**Pull request by viktormaruna**
Power BI Projects currently not supported in Microsoft Power BI Desktop (Optimized for Power BI Report Server).

### CODE REVIEW

**Comment by Court72** [comment]
@RuiRomano 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
asked @mberdugo and @KesemSharabi to review.

**Comment by maggiesMSFT** [comment]
@mberdugo to review

**Comment by mberdugo** [comment]
#aign-off

**Pull request merged**
