### PR TITLE
Quick insights does not require two tables.

### PR DESCRIPTION
**Pull request by eugman**
I was able to run Quick Insights against a single table (Adventureworks.Sales,SalesOrderHeader) without any issues. It does not seem to require a fact table AND a dimension table.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@eugman : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by mihart** [comment]
Hi @maggiesMSFT 
I believe this one goes to you?

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @mihart, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger19** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by maggiesMSFT** [comment]
#sign-off -- signing off on an article that will be mine.

**Pull request merged**
