### PR TITLE
Added 4 snapshot related events to table

### PR DESCRIPTION
**Pull request by talk2rick**
In response to https://github.com/MicrosoftDocs/powerbi-docs/issues/3135

### CODE REVIEW

**Comment by PRMerger15** [comment]
@talk2rick : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by kfollis — APPROVED** [review]

**Comment by kfollis** [comment]
Thanks, @talk2rick! This looks good - you can sign off if you have no other change to make.

**Comment by v-andreaco** [comment]
@kfollis 

This pull request was opened in the public repo, and cannot be viewed on staging. The table additions have three columns, while the rest have 2, which I *think* might cause a formatting error. Will you please move this change to the private repo so that staging can be verified, then close this PR? If you'd like us to take care of that for you, email the techdocprs alias.

Thanks!

**Comment by kfollis** [comment]
Thanks, @v-andreaco - I didn't even notice! Yes, I can easily move this change to private repo and will close this PR.

**Comment by kfollis** [comment]
changes moved to private repo, verified, and committed directly to master (commit 893830a1f35570630f224b8c1457eb87a230dfb8)

**Pull request closed without merging**
