### PR TITLE
Updated Usage Metrics v1 documentation

### PR DESCRIPTION
**Pull request by saurabhr14**
Updated Usage Metrics v1 documentation by replacing MyWorkspace with Report Usage Metrics.
Added limitation "Usage Metrics is not supported in My Workspace." to considerations and limitations section

### CODE REVIEW

**Comment by Court72** [comment]
@maggiesMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
Hi, @saurabhr14 -- thanks for your suggestion. I'm checking with the product team.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by maggiesMSFT** [comment]
replacing with https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/9753

**Pull request closed without merging**
