### PR TITLE
Update service-gateway-sso-kerberos.md

### PR DESCRIPTION
**Pull request by User-sys-code**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@User-sys-code : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by mgblythe** [comment]
Thanks @User-sys-code

**Pull request merged**
