### PR TITLE
Update service-dataflows-promote-certify.md

### PR DESCRIPTION
**Pull request by ibarrau**
Adding a note to clarify that the connection to a promoted dataflow entity is considered a linked entity that requires premium capacity.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@ibarrau : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kfollis** [comment]
@painbar - can you verify the content update and sign-off if all looks correct?

**Comment by PRMerger17** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by paulinbar** [comment]
Hi @ibarrau, sorry for taking so long to get back to you. I looked into your suggestion and talked to the product team, and after some consideration we decided not to adopt your suggestion in this context. Apparently, using dataflow (endorsed) entities doesn’t always require Premium for refresh. If you use a dataflow on top of another dataflow, then yes it does require Premium. But if you just build a dataset on top of a dataflow, then it doesn’t. For this reason, since we are not talking here about the specific case of a dataflow on top of another dataflow, we decided that this is not the right context for a note about a Premium requirement.
I want to thank you for your suggestion, however, and am going to keep it in mind when I review the documentation about dataflows.

**Pull request closed without merging**
