### PR TITLE
Fix pluralization of insights

### PR DESCRIPTION
**Pull request by sqlsauce**
In this sentence, the case is mixed up. If "insights" in this sentence is the product feature, I think it should be treated as singular. If it's not the feature, "works" should be "work." Either way, it's currently mixed singular and plural.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@sqlsauce : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
Hi, @mihart, can you look at this? thx

**Comment by mihart** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@sqlsauce : Thanks for your contribution! The author, @mihart, has been notified to review your proposed change.

**Pull request merged**
