### PR TITLE
Image question

### PR DESCRIPTION
**Pull request by huiwenkong**
On that image, I don't see "Semantic model" mentioned in the text, which can be confusing.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@davidiseminger

The intent of the change in this PR seems to be not to fix the content but to raise an issue. You might want to close this PR and address the issue in a new PR in the private repo. 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ShannonLeavitt** [comment]
Closing/reopening to see if new repo configuration triggers PRMerger

**Comment by ShannonLeavitt** [comment]
#assign:ShannonLeavitt

**Comment by davidiseminger** [comment]
Thanks for your comment - that article is in the process of being updated.

**Pull request closed without merging**
