### PR TITLE
CC74625: Update DAX reference page URL

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @davidiseminger,
This proposed file change comes from https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/pull/4 .
Could you review this contribution and help to merge if agreed?
Many thanks in advance.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@v-makoud : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@mgblythe : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md 
 Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md 
 We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by maggiesMSFT** [comment]
So what's the deal with this PR? Did these changes get made? If not why not?

**Comment by PRMerger18** [comment]
@mgblythe : Thanks for your contribution! The author, @davidiseminger, has been notified to review your proposed change.

**Comment by mgblythe** [comment]
Reopened and merging this. @v-makoud - you should be making changes in the private repo. Let me know if you need help with this. @maggiesMSFT and @davidiseminger as FYI.

**Pull request merged**
