### PR TITLE
Update service-r-packages-support.md

### PR DESCRIPTION
**Pull request by otarb**
Updating package list to latest

### CODE REVIEW

**Comment by PRMerger19** [comment]
@otarb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@otarb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@v-shils : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Jak-MS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
