### PR TITLE
adding on-demand loading capabilities

### PR DESCRIPTION
**Pull request by pawarbi**
I would like request this to be added to the documentation. This is not covered anywhere in the Docs and the users will find it very helpful. 

https://powerbi.microsoft.com/en-us/blog/announcing-on-demand-loading-capabilities-for-large-models-in-power-bi/

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@pawarbi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by KesemSharabi** [comment]
Hi @pawarbi,

Thank you for your contribution. I'm checking the validity of your proposal and once confirmed, I'll add it to the article.

Kesem

**Comment by KesemSharabi** [comment]
Hi @

Thank you for your contribution and for getting involved.

After speaking to the engineering team, we decided not to publish your suggestion. However, I will shortly add a section to the [Large datasets in Power BI Premium](https://docs.microsoft.com/power-bi/enterprise/service-premium-large-models) article, titled *On-demand load*. This section will include some of the text you suggested with small modifications.

Once again, thanks for engaging with us and highlighting this gap!

Kesem

**Pull request closed without merging**
