### PR TITLE
Update license-capabilities.md

### PR DESCRIPTION
**Pull request by haydnr**
Edited

### CODE REVIEW

**Comment by PRMerger18** [comment]
@haydnr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
