### PR TITLE
Added new note

### PR DESCRIPTION
**Pull request by Brspie**
Updated this: 

## Power BI community

If you're unable to create a forum post on the community page, it's because the [Power BI community forum](https://community.powerbi.com/) also requires you to sign in.

> [!Note]
> See this [page](https://community.powerbi.com/t5/Community-Support/ct-p/PBI_CommunitySupport) for additnal details.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Brspie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Brspie** [comment]
@mgblythe for review please

**Comment by PRMerger15** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mgblythe : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mgblythe** [comment]
#sign-off

**Pull request merged**
