### PR TITLE
updating output size limit for R visuals

### PR DESCRIPTION
**Pull request by aphilip94**
We are getting a lot of ICMs on this, so would like to mention the size limit. The original limitation of the output size is 2MB. The 4MB update we implemented hasn’t reached PROD yet, will take 3 more weeks.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@aphilip94 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@aphilip94 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @aphilip94 - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We'll keep this PR open for review and merge, but in the future, would you make content updates in the private repo? Thanks!

**Comment by PRMerger19** [comment]
@davidiseminger : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aphilip94** [comment]
My bad! Thanks for pointing that out! @ktoliver 
 Will make sure to use private repo!

**Pull request merged**
