### PR TITLE
Update compare-report-server-service.md

### PR DESCRIPTION
**Pull request by vcarazo**
Power BI Report Server september 2023 introduces Full Screen Mode feature

### CODE REVIEW

**Comment by vcarazo** [comment]
sorry I closed de pull request by error

**Comment by Court72** [comment]
@maggiesMSFT 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by maggiesMSFT** [comment]
Thanks, @vcarazo -- checking with the product team.

**Comment by maggiesMSFT** [comment]
Thanks, so much, @vcarazo -- product team says yes, good catch!
#sign-off

**Pull request merged**
