### PR TITLE
Update changelog.md

### PR DESCRIPTION
**Pull request by AsafMozes**
fetchMoreData now supports non-aggregation mode.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@AsafMozes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@maggiesMSFT: I'm sorry - only the author of this article, @KesemSharabi, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
