### PR TITLE
Update service-report-subscribe.md

### PR DESCRIPTION
**Pull request by cmfinlan**
Adding a note to clarify when e-mail is actually sent.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@cmfinlan : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mgblythe : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mgblythe : Thanks for your contribution! The author, @maggiesMSFT, has been notified to review your proposed change.

**Comment by mgblythe** [comment]
@cmfinlan - can this and #866 be merged? Reminder to make changes in the private repo (powerbi-docs). Thanks for the updates.

**Comment by cmfinlan** [comment]
I thought I did do that?  But sure, it can be merged

**Pull request merged**
