### PR TITLE
fix: powerbi-docs/includes/gateway-onprem-faq-shared-include.md

### PR DESCRIPTION
**Pull request by nschonni**
- Add code fence language
- accessable -> accessible

### CODE REVIEW

**Comment by PRMerger19** [comment]
@nschonni : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@TrishaMc : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by TrishaMc** [comment]
Editorial and code fence fixes verified.

**Comment by PRMerger19** [comment]
@TrishaMc : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Pull request merged**
