### PR TITLE
Update service-create-distribute-apps.md - For the new custom message feature 

### PR DESCRIPTION
**Pull request by JadelynRay17**
Drafting my content for the new custom message setting for org apps. Need to work on adding images to my sections next

### CODE REVIEW

**Comment by American-Dipper** [comment]
@JadelynRay @maggiesMSFT - This can't be merged with the "Image goes here" lines (two). 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.  
 

#label:"aq-pr-triaged" 

@MicrosoftDocs/public-repo-pr-review-team

**Comment by American-Dipper** [comment]
#hold-off

**Comment by paulinbar** [comment]
Hi @JadelynRay17, is this PR still current or can we close it?

**Comment by paulinbar** [comment]
Dealt with under a different PR.

**Pull request closed without merging**
