### PR TITLE
Fixed link to CircleCard repository

### PR DESCRIPTION
**Pull request by uve**
The correct link is: https://github.com/Microsoft/powerbi-visuals-circlecard

### CODE REVIEW

**Comment by PRMerger6** [comment]
@uve : Thanks for your contribution! The author, @sranins, has been notified to review your proposed change.

**Comment by uve** [comment]
#sign-off
@maggiesMSFT please merge this pr.

**Comment by PRMerger6** [comment]
@uve: I'm sorry - only the author of this article, @sranins, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger19** [comment]
@uve : Thanks for your contribution! The author, @sranins, has been notified to review your proposed change.

**Comment by sranins** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author, @sranins, has been notified to review your proposed change.

**Pull request merged**
