### PR TITLE
Update service-embed-report-microsoft-teams.md

### PR DESCRIPTION
**Pull request by tusharvaja**
Removed a typo. There is not such thing as Power BI BOT service.  @LukaszPawlowski-MS

### CODE REVIEW

**Comment by PRMerger19** [comment]
@tusharvaja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@LukaszPawlowski-MS - Could you review this pull request? Thanks.

**Comment by PRMerger16** [comment]
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by maggiesMSFT** [comment]
#sign-off

**Pull request merged**
