### PR TITLE
Create anaplan-connector.md

### PR DESCRIPTION
**Pull request by goyash17**
Anaplan connector is going live on Nov 9th as per PowerBI certification team. This content covers the functionality of Anaplan Connector in PowerBI.

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @goyash17 - Thank you for your new content submission. Would you take a moment to sign the Contributor License Agreement (CLA)? After the CLA is signed, someone can review your pull request. Thanks!

**Comment by ktoliver** [comment]
@goyash17 Thanks for signing the CLA. The content team will review the content submission. Thanks!

**Comment by maggiesMSFT** [comment]
Thanks for your submission, @goyash17 ! Assigned to 2 Power BI authors to review.

**Comment by cpopell** [comment]
Hi @goyash17 , a couple points

1. You should probably submit this to https://github.com/MicrosoftDocs/powerquery-docs/ under the Connectors section
2. You should follow the format seen for connectors in https://docs.microsoft.com/power-query/

**Comment by maggiesMSFT** [comment]
Hi, @goyash17 -- closing this PR because @chanaveer created a replacement PR in the Power Query repo, https://github.com/MicrosoftDocs/powerquery-docs/pull/75

**Pull request closed without merging**
