### PR TITLE
Update report theme documentation

### PR DESCRIPTION
**Pull request by yelper**
Updating the documentation for the [report theme doc page](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes).

This PR currently contains edits up until the `visualStyles` section, which I still have some open questions on (can we use an accordion control or similar to minimize the space used and to let people jump to relevant sections?).

I'm also curious if we can have subtitles (titles with \#\#\# level) be itemized in the table of contents (or if there is a way to implicitly generate a table of contents under particular second-level headings [\#\#]).

This resolves PBI internal bug 223060 (for my reference).

### CODE REVIEW

**Comment by PRMerger13** [comment]
@yelper : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@davidiseminger Could you review the proposed changes? If they're approved, we would like to move the commit to the private repo so we can verify the changes on staging. Thanks!

**Comment by yelper** [comment]
@ktoliver I can make a PR in the private repo if that's easier.

**Comment by ktoliver** [comment]
@yelper Yes, that would be good. Could you close this PR when you've done that? Thanks!

**Comment by PRMerger9** [comment]
@yelper : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by yelper** [comment]
Canceling PR in favor of internal repo (opened [PR 3213](https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/3213) there).

**Pull request closed without merging**
